-- VMaNGOS Database Chinese script
-- Author: Mr.huang (QQ: 654706160)
-- Create time: 2019-07-11 16:12:37
-- File name: mangos_string.sql
-- Table name: mangos_string

USE `mangos`;
SET NAMES 'utf-8';

UPDATE `mangos_string` SET `content_loc4`="你需要选择一个玩家角色或者生物" WHERE `entry`=1;
UPDATE `mangos_string` SET `content_loc4`="你需要选择一个生物" WHERE `entry`=2;
UPDATE `mangos_string` SET `content_loc4`="|cffff0000[系统消息]: %s|r" WHERE `entry`=3;
UPDATE `mangos_string` SET `content_loc4`="|cffff0000[事件消息]: %s|r" WHERE `entry`=4;
UPDATE `mangos_string` SET `content_loc4`="这个命令没有帮助" WHERE `entry`=5;
UPDATE `mangos_string` SET `content_loc4`="没有这样的命令" WHERE `entry`=6;
UPDATE `mangos_string` SET `content_loc4`="没有这样的子命令" WHERE `entry`=7;
UPDATE `mangos_string` SET `content_loc4`="命令%s有子命令:" WHERE `entry`=8;
UPDATE `mangos_string` SET `content_loc4`="你可使用的命令:" WHERE `entry`=9;
UPDATE `mangos_string` SET `content_loc4`="语法错误。" WHERE `entry`=10;
UPDATE `mangos_string` SET `content_loc4`="你的账号等级是:%i" WHERE `entry`=11;
UPDATE `mangos_string` SET `content_loc4`="在线玩家：%u(最大:%u) 排队玩家：%u(最大:%u)" WHERE `entry`=12;
UPDATE `mangos_string` SET `content_loc4`="服务器正常运行时间:%s" WHERE `entry`=13;
UPDATE `mangos_string` SET `content_loc4`="玩家数据保存成功。" WHERE `entry`=14;
UPDATE `mangos_string` SET `content_loc4`="所有玩家数据保存成功。" WHERE `entry`=15;
UPDATE `mangos_string` SET `content_loc4`="此服务器上有以下活动的GM:" WHERE `entry`=16;
UPDATE `mangos_string` SET `content_loc4`="此服务器上当前没有GM登录。" WHERE `entry`=17;
UPDATE `mangos_string` SET `content_loc4`="飞行时不能那样做" WHERE `entry`=18;
UPDATE `mangos_string` SET `content_loc4`="战场中不能那样做" WHERE `entry`=19;
UPDATE `mangos_string` SET `content_loc4`="目标在飞行中，你不能那样做" WHERE `entry`=20;
UPDATE `mangos_string` SET `content_loc4`="%s飞行命令失败。" WHERE `entry`=21;
UPDATE `mangos_string` SET `content_loc4`="没有上马，因此你不能下马" WHERE `entry`=22;
UPDATE `mangos_string` SET `content_loc4`="战斗中不能那样做" WHERE `entry`=23;
UPDATE `mangos_string` SET `content_loc4`="你最近刚使用过" WHERE `entry`=24;
UPDATE `mangos_string` SET `content_loc4`="密码未更改(未知错误)" WHERE `entry`=25;
UPDATE `mangos_string` SET `content_loc4`="密码修改成功。" WHERE `entry`=26;
UPDATE `mangos_string` SET `content_loc4`="旧密码错误。" WHERE `entry`=27;
UPDATE `mangos_string` SET `content_loc4`="你的帐号被锁定了" WHERE `entry`=28;
UPDATE `mangos_string` SET `content_loc4`="你的账号解锁了" WHERE `entry`=29;
UPDATE `mangos_string` SET `content_loc4`=",等级" WHERE `entry`=30;
UPDATE `mangos_string` SET `content_loc4`="[已知]" WHERE `entry`=31;
UPDATE `mangos_string` SET `content_loc4`="[学习]" WHERE `entry`=32;
UPDATE `mangos_string` SET `content_loc4`="[被动]" WHERE `entry`=33;
UPDATE `mangos_string` SET `content_loc4`="[人才]" WHERE `entry`=34;
UPDATE `mangos_string` SET `content_loc4`="[活动]" WHERE `entry`=35;
UPDATE `mangos_string` SET `content_loc4`="[完成]" WHERE `entry`=36;
UPDATE `mangos_string` SET `content_loc4`="(离线)" WHERE `entry`=37;
UPDATE `mangos_string` SET `content_loc4`="开" WHERE `entry`=38;
UPDATE `mangos_string` SET `content_loc4`="关" WHERE `entry`=39;
UPDATE `mangos_string` SET `content_loc4`="你是:%s" WHERE `entry`=40;
UPDATE `mangos_string` SET `content_loc4`="可见" WHERE `entry`=41;
UPDATE `mangos_string` SET `content_loc4`="隐形" WHERE `entry`=42;
UPDATE `mangos_string` SET `content_loc4`="完成" WHERE `entry`=43;
UPDATE `mangos_string` SET `content_loc4`="你" WHERE `entry`=44;
UPDATE `mangos_string` SET `content_loc4`="<未知>" WHERE `entry`=45;
UPDATE `mangos_string` SET `content_loc4`="<错误>" WHERE `entry`=46;
UPDATE `mangos_string` SET `content_loc4`="<角色不存在>" WHERE `entry`=47;
UPDATE `mangos_string` SET `content_loc4`="未知" WHERE `entry`=48;
UPDATE `mangos_string` SET `content_loc4`="你至少需要达到%u级才能进入" WHERE `entry`=49;
UPDATE `mangos_string` SET `content_loc4`="你必须持有%s才能进入" WHERE `entry`=50;
UPDATE `mangos_string` SET `content_loc4`="你好！准备好接收训练了吗？" WHERE `entry`=51;
UPDATE `mangos_string` SET `content_loc4`="%u项目计数无效" WHERE `entry`=52;
UPDATE `mangos_string` SET `content_loc4`="%u项目不能有更多的堆栈" WHERE `entry`=53;
UPDATE `mangos_string` SET `content_loc4`="新旧密码不匹配" WHERE `entry`=54;
UPDATE `mangos_string` SET `content_loc4`="你的密码长度不能超过16个字符（客户端限制），密码未更改" WHERE `entry`=55;
UPDATE `mangos_string` SET `content_loc4`="今日消息：%s" WHERE `entry`=56;
UPDATE `mangos_string` SET `content_loc4`="使用世界数据库:%s" WHERE `entry`=57;
UPDATE `mangos_string` SET `content_loc4`="使用脚本库:%s" WHERE `entry`=58;
UPDATE `mangos_string` SET `content_loc4`="使用生物事件:%s" WHERE `entry`=59;
UPDATE `mangos_string` SET `content_loc4`="账号:" WHERE `entry`=61;
UPDATE `mangos_string` SET `content_loc4`="密码:" WHERE `entry`=62;
UPDATE `mangos_string` SET `content_loc4`="接受悄悄话" WHERE `entry`=63;
UPDATE `mangos_string` SET `content_loc4`="不接受悄悄话" WHERE `entry`=64;
UPDATE `mangos_string` SET `content_loc4`="使用脚本库:<未知脚本库>" WHERE `entry`=65;
UPDATE `mangos_string` SET `content_loc4`="使用脚本库:<未加载脚本库>" WHERE `entry`=66;
UPDATE `mangos_string` SET `content_loc4`="全体注意：" WHERE `entry`=100;
UPDATE `mangos_string` SET `content_loc4`="%s正在被传送中" WHERE `entry`=102;
UPDATE `mangos_string` SET `content_loc4`="只有对方在你的队伍中并且你是队长才能召唤他到你附近" WHERE `entry`=103;
UPDATE `mangos_string` SET `content_loc4`="你不能传送到玩家的副本，因为你们不在与一队伍。" WHERE `entry`=104;
UPDATE `mangos_string` SET `content_loc4`="传送到不是同一队伍的玩家的副本需要打开GM模式。" WHERE `entry`=105;
UPDATE `mangos_string` SET `content_loc4`="你不能传送到玩家 %s 从副本到副本。" WHERE `entry`=106;
UPDATE `mangos_string` SET `content_loc4`="你不能召唤这个玩家 %s 从副本到副本。" WHERE `entry`=107;
UPDATE `mangos_string` SET `content_loc4`="你正在召唤 %s%s。" WHERE `entry`=108;
UPDATE `mangos_string` SET `content_loc4`="你正在被 %s 召唤中。" WHERE `entry`=109;
UPDATE `mangos_string` SET `content_loc4`="你正在传送 %s%s 到 %s。" WHERE `entry`=110;
UPDATE `mangos_string` SET `content_loc4`="你正在被 %s 传送。" WHERE `entry`=111;
UPDATE `mangos_string` SET `content_loc4`="玩家 (%s) 不存在。" WHERE `entry`=112;
UPDATE `mangos_string` SET `content_loc4`="出现在 %s 的地点 (在线)。" WHERE `entry`=113;
UPDATE `mangos_string` SET `content_loc4`="%s 出现在你的位置。" WHERE `entry`=114;
UPDATE `mangos_string` SET `content_loc4`="无效参数。" WHERE `entry`=115;
UPDATE `mangos_string` SET `content_loc4`="没有选定角色。" WHERE `entry`=116;
UPDATE `mangos_string` SET `content_loc4`="%s不在一个队伍中" WHERE `entry`=117;
UPDATE `mangos_string` SET `content_loc4`="你改变了 %s 的血量值 HP 到 %i/%i。" WHERE `entry`=118;
UPDATE `mangos_string` SET `content_loc4`="%s 改变了你的血量值 HP 到 %i/%i。" WHERE `entry`=119;
UPDATE `mangos_string` SET `content_loc4`="你改变了 %s 的魔法值到 %i/%i。" WHERE `entry`=120;
UPDATE `mangos_string` SET `content_loc4`="%s 改变了你的魔法值到 %i/%i。" WHERE `entry`=121;
UPDATE `mangos_string` SET `content_loc4`="你改变了 %s 的能量值能源到 %i/%i。" WHERE `entry`=122;
UPDATE `mangos_string` SET `content_loc4`="%s 改变了你的能量值能源到 %i/%i。" WHERE `entry`=123;
UPDATE `mangos_string` SET `content_loc4`="当前的能量: %u" WHERE `entry`=124;
UPDATE `mangos_string` SET `content_loc4`="你改变了 %s 的怒气值愤怒到 %i/%i。" WHERE `entry`=125;
UPDATE `mangos_string` SET `content_loc4`="%s 改变了你的怒气值愤怒到 %i/%i。" WHERE `entry`=126;
UPDATE `mangos_string` SET `content_loc4`="你改变了 %s 的等级到 % i。" WHERE `entry`=127;
UPDATE `mangos_string` SET `content_loc4`="GUID%i, 阵营是 %i, 旗子是 %i, npcflag 是 %i, DY 旗子是 %i" WHERE `entry`=128;
UPDATE `mangos_string` SET `content_loc4`="错误阵式: %u.(在 factiontemplate.dbc 中没找到)" WHERE `entry`=129;
UPDATE `mangos_string` SET `content_loc4`="你改变了 GUID=%i 阵营到 %i, 旗子到 %i, NPC旗子到 %i, DY旗子到 %i。" WHERE `entry`=130;
UPDATE `mangos_string` SET `content_loc4`="%s 获得了所有的计程节点 (直到注销)" WHERE `entry`=133;
UPDATE `mangos_string` SET `content_loc4`="%s 没有更多地可获得的计程节点 (仅显示容易接近的)" WHERE `entry`=134;
UPDATE `mangos_string` SET `content_loc4`="%s 给你进入所有计程车节点 (直到注销)" WHERE `entry`=135;
UPDATE `mangos_string` SET `content_loc4`="%s 已取消进出所有计程节点 (仅显示仍然容易接近的)" WHERE `entry`=136;
UPDATE `mangos_string` SET `content_loc4`="您将所有速度从正常的%s设置为%2.2f。" WHERE `entry`=137;
UPDATE `mangos_string` SET `content_loc4`="%s将您的所有速度从正常设置为%2.2f。" WHERE `entry`=138;
UPDATE `mangos_string` SET `content_loc4`="您将%s的移动速度从正常设置为%2.2f。" WHERE `entry`=139;
UPDATE `mangos_string` SET `content_loc4`="%s将你的移动速度从正常设置为%2.2f。" WHERE `entry`=140;
UPDATE `mangos_string` SET `content_loc4`="您将游泳速度从正常的%s设置为%2.2f。" WHERE `entry`=141;
UPDATE `mangos_string` SET `content_loc4`="%s将您的游泳速度从正常设置为%2.2f。" WHERE `entry`=142;
UPDATE `mangos_string` SET `content_loc4`="将向后运行速度从正常的%s设置为%2.2f。" WHERE `entry`=143;
UPDATE `mangos_string` SET `content_loc4`="%s将您的向后运行速度从正常设置为%2.2f。" WHERE `entry`=144;
UPDATE `mangos_string` SET `content_loc4`="你将%s的比例设置为 %2.2f。" WHERE `entry`=147;
UPDATE `mangos_string` SET `content_loc4`="%s将你的比例设置为%2.2f。" WHERE `entry`=148;
UPDATE `mangos_string` SET `content_loc4`="没有这样的坐骑。" WHERE `entry`=149;
UPDATE `mangos_string` SET `content_loc4`="你把一个骑术送给 %s。" WHERE `entry`=150;
UPDATE `mangos_string` SET `content_loc4`="%s 送给你一个骑术。" WHERE `entry`=151;
UPDATE `mangos_string` SET `content_loc4`="用户1: %i，增加: %i， 结果: %i" WHERE `entry`=152;
UPDATE `mangos_string` SET `content_loc4`="你从 %s 拿走了所有的铜币。" WHERE `entry`=153;
UPDATE `mangos_string` SET `content_loc4`="%s 拿走了你的所有铜币。" WHERE `entry`=154;
UPDATE `mangos_string` SET `content_loc4`="你从 %s 这拿走了 %i 个铜币。" WHERE `entry`=155;
UPDATE `mangos_string` SET `content_loc4`="%s 从你这拿走 %i  个铜币。" WHERE `entry`=156;
UPDATE `mangos_string` SET `content_loc4`="你将 %i 个铜币给了 %s。" WHERE `entry`=157;
UPDATE `mangos_string` SET `content_loc4`="%s 给了你 %i 个铜币。" WHERE `entry`=158;
UPDATE `mangos_string` SET `content_loc4`="你听到声音 %u。" WHERE `entry`=159;
UPDATE `mangos_string` SET `content_loc4`="用户2: %i，增加: %i， 结果: %i" WHERE `entry`=160;
UPDATE `mangos_string` SET `content_loc4`="移除 %i 位在字段 %i中。" WHERE `entry`=161;
UPDATE `mangos_string` SET `content_loc4`="设置 %i 位在字段 %i 中。" WHERE `entry`=162;
UPDATE `mangos_string` SET `content_loc4`="传送点数据表是空的！" WHERE `entry`=163;
UPDATE `mangos_string` SET `content_loc4`="没有找到传送点。" WHERE `entry`=164;
UPDATE `mangos_string` SET `content_loc4`="需要搜索参数。" WHERE `entry`=165;
UPDATE `mangos_string` SET `content_loc4`="没有与您的请求匹配的传送点。" WHERE `entry`=166;
UPDATE `mangos_string` SET `content_loc4`="发现传送点：\r\n%s" WHERE `entry`=168;
UPDATE `mangos_string` SET `content_loc4`="发送邮件至 %s" WHERE `entry`=169;
UPDATE `mangos_string` SET `content_loc4`="你尝试听到声音 %u， 但它并不存在。" WHERE `entry`=170;
UPDATE `mangos_string` SET `content_loc4`="你不能传送自己到自己！" WHERE `entry`=171;
UPDATE `mangos_string` SET `content_loc4`="服务器控制台命令" WHERE `entry`=172;
UPDATE `mangos_string` SET `content_loc4`="没有选择。" WHERE `entry`=200;
UPDATE `mangos_string` SET `content_loc4`="%i 角色名字太长。" WHERE `entry`=202;
UPDATE `mangos_string` SET `content_loc4`="错误，角色名称只能包含字符A-Z和a-z。" WHERE `entry`=203;
UPDATE `mangos_string` SET `content_loc4`="角色 %i 的次级名字 太长了。" WHERE `entry`=204;
UPDATE `mangos_string` SET `content_loc4`="没有实现。" WHERE `entry`=205;
UPDATE `mangos_string` SET `content_loc4`="物品 '%i' '%s' 以加入到清单且最大数 '%i' 复活时间 '%i'" WHERE `entry`=206;
UPDATE `mangos_string` SET `content_loc4`="数据库里找不到物品 '%i'" WHERE `entry`=207;
UPDATE `mangos_string` SET `content_loc4`="物品 '%i' '%s' 已经从商人清单中删除。" WHERE `entry`=208;
UPDATE `mangos_string` SET `content_loc4`="在商人的清单里中没有找到物品 '%i'。" WHERE `entry`=209;
UPDATE `mangos_string` SET `content_loc4`="在商人的清单里中找到了物品 '%i'。" WHERE `entry`=210;
UPDATE `mangos_string` SET `content_loc4`="法术 %s 重置。" WHERE `entry`=211;
UPDATE `mangos_string` SET `content_loc4`="法术 %s 将在下次登陆时重置。" WHERE `entry`=212;
UPDATE `mangos_string` SET `content_loc4`="天赋 %s 重置。" WHERE `entry`=213;
UPDATE `mangos_string` SET `content_loc4`="天赋 %s 将在下次登陆时重置。" WHERE `entry`=214;
UPDATE `mangos_string` SET `content_loc4`="你的技能已经重置了" WHERE `entry`=215;
UPDATE `mangos_string` SET `content_loc4`="你的天赋已经重置了" WHERE `entry`=216;
UPDATE `mangos_string` SET `content_loc4`="未知的参数 '%s' 为.resetall指令。 请正确输入完整的参数名字。" WHERE `entry`=217;
UPDATE `mangos_string` SET `content_loc4`="所有玩家的法术将在重新登录时重置。强烈建议重新登录！" WHERE `entry`=218;
UPDATE `mangos_string` SET `content_loc4`="所有玩家的天赋将在重新登录时重置。强烈建议重新登录！" WHERE `entry`=219;
UPDATE `mangos_string` SET `content_loc4`="飞行点 %s无法找到飞行点ID %u (在路径%i中，从%s加载)" WHERE `entry`=220;
UPDATE `mangos_string` SET `content_loc4`="未找到飞行目的地 %s" WHERE `entry`=221;
UPDATE `mangos_string` SET `content_loc4`="%s没有路径或路径为空，路径id %i(从%s加载)" WHERE `entry`=222;
UPDATE `mangos_string` SET `content_loc4`="生物 (GUID: %u) 没有飞行点发现 - 这是MaNGOS数据库问题 (单精度浮点数)" WHERE `entry`=223;
UPDATE `mangos_string` SET `content_loc4`="无法在地图上访问%s，可能您离它的衍生位置太远了" WHERE `entry`=224;
UPDATE `mangos_string` SET `content_loc4`="生物 (GUID: %u) 没有找到。" WHERE `entry`=225;
UPDATE `mangos_string` SET `content_loc4`="您必须选择一个可视的飞行点。" WHERE `entry`=226;
UPDATE `mangos_string` SET `content_loc4`="没有找到可视的飞行点。" WHERE `entry`=227;
UPDATE `mangos_string` SET `content_loc4`="无法使用creatureID: %d 创建可视飞行点" WHERE `entry`=228;
UPDATE `mangos_string` SET `content_loc4`="所有的可视飞行点被移除。" WHERE `entry`=229;
UPDATE `mangos_string` SET `content_loc4`="不能将飞行点 %u 添加到 %s (pathId %i 由 %s 存储)" WHERE `entry`=230;
UPDATE `mangos_string` SET `content_loc4`="没有提供GUID。" WHERE `entry`=231;
UPDATE `mangos_string` SET `content_loc4`="没有提供飞行点数值。" WHERE `entry`=232;
UPDATE `mangos_string` SET `content_loc4`="'%s' 需要提供参数。" WHERE `entry`=233;
UPDATE `mangos_string` SET `content_loc4`="将飞行点 %u 添加到 %s (PathId %i, 路径由 %s 存储)" WHERE `entry`=234;
UPDATE `mangos_string` SET `content_loc4`="不可用" WHERE `entry`=235;
UPDATE `mangos_string` SET `content_loc4`="飞行点更改成功。" WHERE `entry`=236;
UPDATE `mangos_string` SET `content_loc4`="飞行点 %s 已修改。" WHERE `entry`=237;
UPDATE `mangos_string` SET `content_loc4`="飞行点输出成功。" WHERE `entry`=238;
UPDATE `mangos_string` SET `content_loc4`="在数据库中没有找到飞行点。" WHERE `entry`=239;
UPDATE `mangos_string` SET `content_loc4`="文件导出成功。" WHERE `entry`=240;
UPDATE `mangos_string` SET `content_loc4`="移除飞行点成功。" WHERE `entry`=241;
UPDATE `mangos_string` SET `content_loc4`="不可用" WHERE `entry`=242;
UPDATE `mangos_string` SET `content_loc4`="不可用" WHERE `entry`=243;
UPDATE `mangos_string` SET `content_loc4`="不可用" WHERE `entry`=244;
UPDATE `mangos_string` SET `content_loc4`="不可用" WHERE `entry`=245;
UPDATE `mangos_string` SET `content_loc4`="%s 的飞行点 %u(来自pathId %i, 由 %s 存储)" WHERE `entry`=246;
UPDATE `mangos_string` SET `content_loc4`="等待时间： %d" WHERE `entry`=247;
UPDATE `mangos_string` SET `content_loc4`="方向：%f" WHERE `entry`=248;
UPDATE `mangos_string` SET `content_loc4`="脚本ID：%s" WHERE `entry`=249;
UPDATE `mangos_string` SET `content_loc4`="脚本ID设置为不存在id %u，将其添加到DBScriptsEngine并重新加载数据表。" WHERE `entry`=250;
UPDATE `mangos_string` SET `content_loc4`="不可用" WHERE `entry`=251;
UPDATE `mangos_string` SET `content_loc4`="AI脚本名称：%s" WHERE `entry`=252;
UPDATE `mangos_string` SET `content_loc4`="强制修改玩家名 %s ，将于下次登录时生效。" WHERE `entry`=253;
UPDATE `mangos_string` SET `content_loc4`="强制修改玩家名 %s(GUID#%u) ，将于下次登录时生效。" WHERE `entry`=254;
UPDATE `mangos_string` SET `content_loc4`="飞行点-生物 (GUID: %u) 没有找到。" WHERE `entry`=255;
UPDATE `mangos_string` SET `content_loc4`="找不到NPC..." WHERE `entry`=256;
UPDATE `mangos_string` SET `content_loc4`="生物运动类型设置为 '%s', 飞行点被移除 (如果有的话)。" WHERE `entry`=257;
UPDATE `mangos_string` SET `content_loc4`="生物运动类型设置为 '%s'，飞行点没有被移除。" WHERE `entry`=258;
UPDATE `mangos_string` SET `content_loc4`="错误值，请使用开(on)或关(off)" WHERE `entry`=259;
UPDATE `mangos_string` SET `content_loc4`="值保存成功。" WHERE `entry`=260;
UPDATE `mangos_string` SET `content_loc4`="值保存成功，可能需要重新联接或清理客户机缓存。" WHERE `entry`=261;
UPDATE `mangos_string` SET `content_loc4`="未找到传送门ID %u！" WHERE `entry`=262;
UPDATE `mangos_string` SET `content_loc4`="目标地图或坐标无效  (X:%f   Y:%f  MapId:%u)" WHERE `entry`=263;
UPDATE `mangos_string` SET `content_loc4`="本地传送门无效 (X:%f Y:%f AreaId:%u)" WHERE `entry`=264;
UPDATE `mangos_string` SET `content_loc4`="区域 %u (%s) 是不稳定映射地图 %u (%s) 的一部分" WHERE `entry`=265;
UPDATE `mangos_string` SET `content_loc4`="没有找到！" WHERE `entry`=266;
UPDATE `mangos_string` SET `content_loc4`="对象没找到！" WHERE `entry`=267;
UPDATE `mangos_string` SET `content_loc4`="生物没找到！" WHERE `entry`=268;
UPDATE `mangos_string` SET `content_loc4`="生物已经删除！" WHERE `entry`=270;
UPDATE `mangos_string` SET `content_loc4`="生物已经移动！" WHERE `entry`=271;
UPDATE `mangos_string` SET `content_loc4`="生物 (GUID:%u) 必须和玩家在同一地图上！" WHERE `entry`=272;
UPDATE `mangos_string` SET `content_loc4`="游戏对象 (GUID: %u) 未找到！" WHERE `entry`=273;
UPDATE `mangos_string` SET `content_loc4`="游戏对象 (GUID: %u) 在所有者 %s 的名单中没有找到引用。无法删除。" WHERE `entry`=274;
UPDATE `mangos_string` SET `content_loc4`="游戏对像 (GUID: %u) 移除。" WHERE `entry`=275;
UPDATE `mangos_string` SET `content_loc4`="游戏对象 |cffffffff|Hgameobject:%d|h[%s]|h|r (GUID: %u) 转移" WHERE `entry`=276;
UPDATE `mangos_string` SET `content_loc4`="游戏对象 |cffffffff|Hgameobject:%d|h[%s]|h|r (GUID: %u) 移动" WHERE `entry`=277;
UPDATE `mangos_string` SET `content_loc4`="你必须选择一个商人" WHERE `entry`=278;
UPDATE `mangos_string` SET `content_loc4`="你必须发送id到物品" WHERE `entry`=279;
UPDATE `mangos_string` SET `content_loc4`="商人设置了太多的物品 (最多 128)" WHERE `entry`=280;
UPDATE `mangos_string` SET `content_loc4`="你不能踢除你自己，而是退出" WHERE `entry`=281;
UPDATE `mangos_string` SET `content_loc4`="玩家 %s 被踢出" WHERE `entry`=282;
UPDATE `mangos_string` SET `content_loc4`="接受悄悄话: %s" WHERE `entry`=284;
UPDATE `mangos_string` SET `content_loc4`="接受悄悄话: 开" WHERE `entry`=285;
UPDATE `mangos_string` SET `content_loc4`="接受悄悄话: 关" WHERE `entry`=286;
UPDATE `mangos_string` SET `content_loc4`="生物 (GUID: %u) 没有找到。" WHERE `entry`=287;
UPDATE `mangos_string` SET `content_loc4`="票数量: %i 出示新的票: %s" WHERE `entry`=288;
UPDATE `mangos_string` SET `content_loc4`="新票开始于 %s" WHERE `entry`=289;
UPDATE `mangos_string` SET `content_loc4`="票 %s (最后的更新: %s):%s" WHERE `entry`=290;
UPDATE `mangos_string` SET `content_loc4`="新票显示:开" WHERE `entry`=291;
UPDATE `mangos_string` SET `content_loc4`="新票显示:关" WHERE `entry`=292;
UPDATE `mangos_string` SET `content_loc4`="票 %i 不存在。" WHERE `entry`=293;
UPDATE `mangos_string` SET `content_loc4`="所有票已删除。" WHERE `entry`=294;
UPDATE `mangos_string` SET `content_loc4`="角色 %s 票已删除。" WHERE `entry`=295;
UPDATE `mangos_string` SET `content_loc4`="票删除成功。" WHERE `entry`=296;
UPDATE `mangos_string` SET `content_loc4`="复活间隔改变为: %i" WHERE `entry`=297;
UPDATE `mangos_string` SET `content_loc4`="复活时间改变为: %i" WHERE `entry`=298;
UPDATE `mangos_string` SET `content_loc4`="%s 的荣誉被设置到 %u!" WHERE `entry`=299;
UPDATE `mangos_string` SET `content_loc4`="你被禁言%u分钟" WHERE `entry`=300;
UPDATE `mangos_string` SET `content_loc4`="你对 %s 禁言%u分钟" WHERE `entry`=301;
UPDATE `mangos_string` SET `content_loc4`="玩家的禁言已经解除" WHERE `entry`=302;
UPDATE `mangos_string` SET `content_loc4`="你的禁言已经解除" WHERE `entry`=303;
UPDATE `mangos_string` SET `content_loc4`="你已经解除了%s的禁言" WHERE `entry`=304;
UPDATE `mangos_string` SET `content_loc4`="阵营 %s (%u) 荣誉 %s 被设置成 %5d!" WHERE `entry`=305;
UPDATE `mangos_string` SET `content_loc4`="没有发现阵营！" WHERE `entry`=307;
UPDATE `mangos_string` SET `content_loc4`="阵营 %i 未知。" WHERE `entry`=308;
UPDATE `mangos_string` SET `content_loc4`="无效的参数 %s" WHERE `entry`=309;
UPDATE `mangos_string` SET `content_loc4`="delta必须在0到%d之间（包括0和%d）" WHERE `entry`=310;
UPDATE `mangos_string` SET `content_loc4`="[可见]" WHERE `entry`=312;
UPDATE `mangos_string` SET `content_loc4`="[在战争]" WHERE `entry`=313;
UPDATE `mangos_string` SET `content_loc4`="[和平被迫]" WHERE `entry`=314;
UPDATE `mangos_string` SET `content_loc4`="[隐藏]" WHERE `entry`=315;
UPDATE `mangos_string` SET `content_loc4`="[无形强制]" WHERE `entry`=316;
UPDATE `mangos_string` SET `content_loc4`="[非活动]" WHERE `entry`=317;
UPDATE `mangos_string` SET `content_loc4`="仇恨" WHERE `entry`=318;
UPDATE `mangos_string` SET `content_loc4`="敌对" WHERE `entry`=319;
UPDATE `mangos_string` SET `content_loc4`="不友好" WHERE `entry`=320;
UPDATE `mangos_string` SET `content_loc4`="中立" WHERE `entry`=321;
UPDATE `mangos_string` SET `content_loc4`="友好的" WHERE `entry`=322;
UPDATE `mangos_string` SET `content_loc4`="荣誉的" WHERE `entry`=323;
UPDATE `mangos_string` SET `content_loc4`="尊敬的" WHERE `entry`=324;
UPDATE `mangos_string` SET `content_loc4`="高贵的" WHERE `entry`=325;
UPDATE `mangos_string` SET `content_loc4`="阵营 %s (%u) 不能有荣誉。" WHERE `entry`=326;
UPDATE `mangos_string` SET `content_loc4`="[没有荣誉]" WHERE `entry`=327;
UPDATE `mangos_string` SET `content_loc4`="在帐户的角色 %s (ID: %u)" WHERE `entry`=328;
UPDATE `mangos_string` SET `content_loc4`="没有发现玩家！" WHERE `entry`=330;
UPDATE `mangos_string` SET `content_loc4`="扩展物品费用 %u 不存在" WHERE `entry`=331;
UPDATE `mangos_string` SET `content_loc4`="GM模式开启" WHERE `entry`=332;
UPDATE `mangos_string` SET `content_loc4`="GM模式关闭" WHERE `entry`=333;
UPDATE `mangos_string` SET `content_loc4`="GM聊天频道标记开启" WHERE `entry`=334;
UPDATE `mangos_string` SET `content_loc4`="GM聊天频道标记关闭" WHERE `entry`=335;
UPDATE `mangos_string` SET `content_loc4`="你修理所有的 %s 物品" WHERE `entry`=336;
UPDATE `mangos_string` SET `content_loc4`="你所有的物品都按%s修理。" WHERE `entry`=337;
UPDATE `mangos_string` SET `content_loc4`="您将水上行走模式%s设置为%s。" WHERE `entry`=338;
UPDATE `mangos_string` SET `content_loc4`="你的水上行走模式%s来自%s。" WHERE `entry`=339;
UPDATE `mangos_string` SET `content_loc4`="%s正在跟随你。" WHERE `entry`=340;
UPDATE `mangos_string` SET `content_loc4`="%s没有跟随你。" WHERE `entry`=341;
UPDATE `mangos_string` SET `content_loc4`="%s立即跟随你。" WHERE `entry`=342;
UPDATE `mangos_string` SET `content_loc4`="生物(Entry:%u)不能被驯服。" WHERE `entry`=343;
UPDATE `mangos_string` SET `content_loc4`="你已经有宠物了" WHERE `entry`=344;
UPDATE `mangos_string` SET `content_loc4`="TaxiNode ID %u 没有找到！" WHERE `entry`=347;
UPDATE `mangos_string` SET `content_loc4`="游戏对象 (Entry: %u) 是无效数据并且无法生成" WHERE `entry`=348;
UPDATE `mangos_string` SET `content_loc4`="传送到 %u 没有目的坐标" WHERE `entry`=357;
UPDATE `mangos_string` SET `content_loc4`="无法传送！" WHERE `entry`=358;
UPDATE `mangos_string` SET `content_loc4`="%s|cffffffff|区域传送目标:%u|h[传送目标 %u]|h|r Map %u X:%f Y:%f Z:%f%s" WHERE `entry`=359;
UPDATE `mangos_string` SET `content_loc4`="%s[传送目标 %u] Map %u X:%f Y:%f Z:%f" WHERE `entry`=360;
UPDATE `mangos_string` SET `content_loc4`="|cffffffff|区域传送:%u|h[传送 %u]|h|r Map %u X:%f Y:%f Z:%f%s%s%s" WHERE `entry`=361;
UPDATE `mangos_string` SET `content_loc4`="[传送 %u] Map %u X:%f Y:%f Z:%f%s%s" WHERE `entry`=362;
UPDATE `mangos_string` SET `content_loc4`="(距离 %f)" WHERE `entry`=363;
UPDATE `mangos_string` SET `content_loc4`="[小酒馆]" WHERE `entry`=364;
UPDATE `mangos_string` SET `content_loc4`="[任务]" WHERE `entry`=365;
UPDATE `mangos_string` SET `content_loc4`="探索任务:" WHERE `entry`=366;
UPDATE `mangos_string` SET `content_loc4`="要求等级 %u" WHERE `entry`=367;
UPDATE `mangos_string` SET `content_loc4`="要求物品:" WHERE `entry`=368;
UPDATE `mangos_string` SET `content_loc4`="要求任务:" WHERE `entry`=369;
UPDATE `mangos_string` SET `content_loc4`="回应:\r\n%s" WHERE `entry`=373;
UPDATE `mangos_string` SET `content_loc4`="门票统计:%i" WHERE `entry`=374;
UPDATE `mangos_string` SET `content_loc4`="玩家 %s 没有门票。" WHERE `entry`=375;
UPDATE `mangos_string` SET `content_loc4`="具有明确机会的生物:" WHERE `entry`=388;
UPDATE `mangos_string` SET `content_loc4`="机会均等的生物:" WHERE `entry`=389;
UPDATE `mangos_string` SET `content_loc4`="具有明确机会的Gameobjects:" WHERE `entry`=390;
UPDATE `mangos_string` SET `content_loc4`="机会均等的Gameobjects:" WHERE `entry`=391;
UPDATE `mangos_string` SET `content_loc4`="没有发现池" WHERE `entry`=395;
UPDATE `mangos_string` SET `content_loc4`="具有明确机会的Pools:" WHERE `entry`=397;
UPDATE `mangos_string` SET `content_loc4`="机会均等的Pools:" WHERE `entry`=398;
UPDATE `mangos_string` SET `content_loc4`="|cffff0000[系统消息]:|r脚本已经重载" WHERE `entry`=400;
UPDATE `mangos_string` SET `content_loc4`="您将帐户%s的安全等级更改为%i。" WHERE `entry`=401;
UPDATE `mangos_string` SET `content_loc4`="%s将您的安全等级更改为%i。" WHERE `entry`=402;
UPDATE `mangos_string` SET `content_loc4`="你的安全等级很低。" WHERE `entry`=403;
UPDATE `mangos_string` SET `content_loc4`="生物移动禁用。" WHERE `entry`=404;
UPDATE `mangos_string` SET `content_loc4`="生物移动启用。" WHERE `entry`=405;
UPDATE `mangos_string` SET `content_loc4`="这个地区的天气无法改变。" WHERE `entry`=406;
UPDATE `mangos_string` SET `content_loc4`="本服务器禁用了天气系统。" WHERE `entry`=407;
UPDATE `mangos_string` SET `content_loc4`="%s 被禁止为 %s。 原因: %s。" WHERE `entry`=408;
UPDATE `mangos_string` SET `content_loc4`="%s 被永久禁止为 %s。" WHERE `entry`=409;
UPDATE `mangos_string` SET `content_loc4`="%s %s 没有找到。" WHERE `entry`=410;
UPDATE `mangos_string` SET `content_loc4`="%s 已解除禁止。说明：%s" WHERE `entry`=411;
UPDATE `mangos_string` SET `content_loc4`="解除对%s的禁止发生错误。" WHERE `entry`=412;
UPDATE `mangos_string` SET `content_loc4`="帐户不存在:%s" WHERE `entry`=413;
UPDATE `mangos_string` SET `content_loc4`="没有这个角色。" WHERE `entry`=414;
UPDATE `mangos_string` SET `content_loc4`="没有这样的 IP 在禁止名单。" WHERE `entry`=415;
UPDATE `mangos_string` SET `content_loc4`="账号 %s 从来没被禁止。" WHERE `entry`=416;
UPDATE `mangos_string` SET `content_loc4`="历史禁止帐户 %s:" WHERE `entry`=417;
UPDATE `mangos_string` SET `content_loc4`="禁止日期:%s 禁止时间:%s 仍然有效:%s 原因:%s 设置:%s" WHERE `entry`=418;
UPDATE `mangos_string` SET `content_loc4`="信息。" WHERE `entry`=419;
UPDATE `mangos_string` SET `content_loc4`="从不" WHERE `entry`=420;
UPDATE `mangos_string` SET `content_loc4`="是" WHERE `entry`=421;
UPDATE `mangos_string` SET `content_loc4`="否" WHERE `entry`=422;
UPDATE `mangos_string` SET `content_loc4`="IP: %s\r\n禁止日期: %s\r\n解禁日期: %s\r\n临时名单: %s\r\n原因: %s\r\n禁止标准: %s" WHERE `entry`=423;
UPDATE `mangos_string` SET `content_loc4`="没有符合的 IP 禁止地址。" WHERE `entry`=424;
UPDATE `mangos_string` SET `content_loc4`="没有符合的帐户。" WHERE `entry`=425;
UPDATE `mangos_string` SET `content_loc4`="没有禁用的账号相符合。" WHERE `entry`=426;
UPDATE `mangos_string` SET `content_loc4`="下面的 IP 地址符合您的格局:" WHERE `entry`=427;
UPDATE `mangos_string` SET `content_loc4`="以下帐户符合您的查询:" WHERE `entry`=428;
UPDATE `mangos_string` SET `content_loc4`="你学会了许多法术/技能。" WHERE `entry`=429;
UPDATE `mangos_string` SET `content_loc4`="你已经学会了所有的会职业法术。" WHERE `entry`=430;
UPDATE `mangos_string` SET `content_loc4`="你已经学会了所有的本职业天赋。" WHERE `entry`=431;
UPDATE `mangos_string` SET `content_loc4`="你已经学会了所有的语言。" WHERE `entry`=432;
UPDATE `mangos_string` SET `content_loc4`="你学会了所有手工艺技能和食谱。" WHERE `entry`=433;
UPDATE `mangos_string` SET `content_loc4`="不能查找 '%s'" WHERE `entry`=434;
UPDATE `mangos_string` SET `content_loc4`="无效的物品ID: %u" WHERE `entry`=435;
UPDATE `mangos_string` SET `content_loc4`="没有找到物品!" WHERE `entry`=436;
UPDATE `mangos_string` SET `content_loc4`="无效的游戏对象ID: %u" WHERE `entry`=437;
UPDATE `mangos_string` SET `content_loc4`="找到物品 %u: %u (库存 %u 邮件 %u 拍卖 %u)" WHERE `entry`=438;
UPDATE `mangos_string` SET `content_loc4`="找到物品对像 %u: %u" WHERE `entry`=439;
UPDATE `mangos_string` SET `content_loc4`="无效的生物ID: %u" WHERE `entry`=440;
UPDATE `mangos_string` SET `content_loc4`="找到生物 %u: %u" WHERE `entry`=441;
UPDATE `mangos_string` SET `content_loc4`="没有地区被发现!" WHERE `entry`=442;
UPDATE `mangos_string` SET `content_loc4`="没有找到物品集!" WHERE `entry`=443;
UPDATE `mangos_string` SET `content_loc4`="没有找到此技能!" WHERE `entry`=444;
UPDATE `mangos_string` SET `content_loc4`="没有找到此法术!" WHERE `entry`=445;
UPDATE `mangos_string` SET `content_loc4`="没有找到此任务!" WHERE `entry`=446;
UPDATE `mangos_string` SET `content_loc4`="没有找到此生物!" WHERE `entry`=447;
UPDATE `mangos_string` SET `content_loc4`="没有找到此游戏物品对像!" WHERE `entry`=448;
UPDATE `mangos_string` SET `content_loc4`="墓地 #%u 不存在。" WHERE `entry`=449;
UPDATE `mangos_string` SET `content_loc4`="墓地 #%u 已经链接到区域 #%u (当前)." WHERE `entry`=450;
UPDATE `mangos_string` SET `content_loc4`="墓地 #%u 链接到地区 #%u (当前)." WHERE `entry`=451;
UPDATE `mangos_string` SET `content_loc4`="墓地 #%u 不能链接到子区域或子区域不存在 #%u (内部错误)。" WHERE `entry`=452;
UPDATE `mangos_string` SET `content_loc4`="墓地中没有 id=#%u 的阵营，请修复你的数据库。" WHERE `entry`=454;
UPDATE `mangos_string` SET `content_loc4`="队伍错误, 请修复你的数据库。" WHERE `entry`=455;
UPDATE `mangos_string` SET `content_loc4`="任何" WHERE `entry`=456;
UPDATE `mangos_string` SET `content_loc4`="联盟" WHERE `entry`=457;
UPDATE `mangos_string` SET `content_loc4`="部落" WHERE `entry`=458;
UPDATE `mangos_string` SET `content_loc4`="墓地 #%u (阵营: %s) 是距离此区域最近的 zone #%u。" WHERE `entry`=459;
UPDATE `mangos_string` SET `content_loc4`="区域 #%u 没有链接墓地。" WHERE `entry`=460;
UPDATE `mangos_string` SET `content_loc4`="地域 #%u 没有一个墓地链接到阵营: %s。" WHERE `entry`=461;
UPDATE `mangos_string` SET `content_loc4`="传送点已经存在！" WHERE `entry`=462;
UPDATE `mangos_string` SET `content_loc4`="添加传送点成功。" WHERE `entry`=463;
UPDATE `mangos_string` SET `content_loc4`="传送点添加失败：数据库错误。" WHERE `entry`=464;
UPDATE `mangos_string` SET `content_loc4`="传送点被删除！" WHERE `entry`=465;
UPDATE `mangos_string` SET `content_loc4`="没有发现飞行点！" WHERE `entry`=466;
UPDATE `mangos_string` SET `content_loc4`="目标单位 (单位) 有 %d 光环:" WHERE `entry`=467;
UPDATE `mangos_string` SET `content_loc4`="目标单位有 %d 光环，类型为%d:" WHERE `entry`=469;
UPDATE `mangos_string` SET `content_loc4`="任务 %u 没有找到。" WHERE `entry`=471;
UPDATE `mangos_string` SET `content_loc4`="任务 %u 从物品开始。为了能正确地工作，请添加物品到库存和开始任务的正常方式: .additem %u" WHERE `entry`=472;
UPDATE `mangos_string` SET `content_loc4`="任务清除。" WHERE `entry`=473;
UPDATE `mangos_string` SET `content_loc4`="[奖赏]" WHERE `entry`=474;
UPDATE `mangos_string` SET `content_loc4`="[完成]" WHERE `entry`=475;
UPDATE `mangos_string` SET `content_loc4`="[活动]" WHERE `entry`=476;
UPDATE `mangos_string` SET `content_loc4`="%s 的飞行模式 %s" WHERE `entry`=477;
UPDATE `mangos_string` SET `content_loc4`="操作码 %u 发送到 %s" WHERE `entry`=478;
UPDATE `mangos_string` SET `content_loc4`="角色加载成功！" WHERE `entry`=479;
UPDATE `mangos_string` SET `content_loc4`="角色加载失败！" WHERE `entry`=480;
UPDATE `mangos_string` SET `content_loc4`="卸载角色成功！" WHERE `entry`=481;
UPDATE `mangos_string` SET `content_loc4`="卸载角色失败！" WHERE `entry`=482;
UPDATE `mangos_string` SET `content_loc4`="魔法 %u 中断，并且不能施放或学习!" WHERE `entry`=483;
UPDATE `mangos_string` SET `content_loc4`="技能 %u (%s) 为玩家 %s 设置为 %u，当前最大设置为 %u (没有永久 (天赋) 奖励)。" WHERE `entry`=484;
UPDATE `mangos_string` SET `content_loc4`="在使用此命令之前，玩家 %s 必须拥有技能 %u (%s)。" WHERE `entry`=485;
UPDATE `mangos_string` SET `content_loc4`="无效技能id (%u)" WHERE `entry`=486;
UPDATE `mangos_string` SET `content_loc4`="你学会了GM默认的法术和技能。" WHERE `entry`=487;
UPDATE `mangos_string` SET `content_loc4`="你已经学了这个法术。" WHERE `entry`=488;
UPDATE `mangos_string` SET `content_loc4`="目标 (%s) 已经学习了那些法术。" WHERE `entry`=489;
UPDATE `mangos_string` SET `content_loc4`="%s 不懂那些法术。" WHERE `entry`=490;
UPDATE `mangos_string` SET `content_loc4`="您已经忘记了那个法术。" WHERE `entry`=491;
UPDATE `mangos_string` SET `content_loc4`="所有的法术冷却清除为 %s。" WHERE `entry`=492;
UPDATE `mangos_string` SET `content_loc4`="法术 %u 冷却清除为 %s。" WHERE `entry`=493;
UPDATE `mangos_string` SET `content_loc4`="指令: Additem, itemId = %i, amount = %i" WHERE `entry`=494;
UPDATE `mangos_string` SET `content_loc4`="指令 : Additemset, itemsetId = %i" WHERE `entry`=495;
UPDATE `mangos_string` SET `content_loc4`="删除物品ID=%i,  amount=%i 从 %s" WHERE `entry`=496;
UPDATE `mangos_string` SET `content_loc4`="不能创建物品 %i (数量: %i)" WHERE `entry`=497;
UPDATE `mangos_string` SET `content_loc4`="你需要提供一个公会名字！" WHERE `entry`=498;
UPDATE `mangos_string` SET `content_loc4`="玩家找不到！" WHERE `entry`=499;
UPDATE `mangos_string` SET `content_loc4`="玩家已经加入了一个公会！" WHERE `entry`=500;
UPDATE `mangos_string` SET `content_loc4`="公会没被创建! (是否已经存在?)" WHERE `entry`=501;
UPDATE `mangos_string` SET `content_loc4`="没有物品从物品库 '%u' 里找到。" WHERE `entry`=502;
UPDATE `mangos_string` SET `content_loc4`="距离: (3D) %f (2D) %f (Exact 3D) %f (Exact 2D) %f yards." WHERE `entry`=503;
UPDATE `mangos_string` SET `content_loc4`="物品 '%i' '%s' 背包 %i" WHERE `entry`=504;
UPDATE `mangos_string` SET `content_loc4`="无效的虚拟物品背包 (%u)" WHERE `entry`=505;
UPDATE `mangos_string` SET `content_loc4`="物品 '%i' '%s' 添加到背包 %i" WHERE `entry`=506;
UPDATE `mangos_string` SET `content_loc4`="物品保存失败！" WHERE `entry`=507;
UPDATE `mangos_string` SET `content_loc4`="%d - 拥有者: %s (guid: %u 帐户: %u) %s" WHERE `entry`=508;
UPDATE `mangos_string` SET `content_loc4`="%d - 寄件人: %s (guid: %u 帐户: %u) 收件人: %s (guid: %u 帐户: %u) %s" WHERE `entry`=509;
UPDATE `mangos_string` SET `content_loc4`="%d - 拥有者: %s (guid: %u 帐户: %u) %s" WHERE `entry`=510;
UPDATE `mangos_string` SET `content_loc4`="错误的链接类型！" WHERE `entry`=511;
UPDATE `mangos_string` SET `content_loc4`="游戏对象 (Entry: %u) 没有找到。" WHERE `entry`=522;
UPDATE `mangos_string` SET `content_loc4`=">> 游戏对象 %s (GUID: %u) 在 %f %f %f. 方向 %f." WHERE `entry`=523;
UPDATE `mangos_string` SET `content_loc4`="选中的物体:\r\n|cffffffff|Hgameobject:%d|h[%s]|h|r GUID: %u ID: %u\r\nX: %f Y: %f Z: %f MapId: %u\r\n方向: %f" WHERE `entry`=524;
UPDATE `mangos_string` SET `content_loc4`=">> 添加游戏对象 '%i' (%s) (GUID: %i) 添加到 '%f %f %f'." WHERE `entry`=525;
UPDATE `mangos_string` SET `content_loc4`="%s (lowguid: %u) 移动生成器堆栈:" WHERE `entry`=526;
UPDATE `mangos_string` SET `content_loc4`="闲置" WHERE `entry`=527;
UPDATE `mangos_string` SET `content_loc4`="随机" WHERE `entry`=528;
UPDATE `mangos_string` SET `content_loc4`="飞行点" WHERE `entry`=529;
UPDATE `mangos_string` SET `content_loc4`="动物随机" WHERE `entry`=530;
UPDATE `mangos_string` SET `content_loc4`="困惑" WHERE `entry`=531;
UPDATE `mangos_string` SET `content_loc4`="目标为玩家 %s (lowguid %u)" WHERE `entry`=532;
UPDATE `mangos_string` SET `content_loc4`="目标为生物 %s (lowguid %u)" WHERE `entry`=533;
UPDATE `mangos_string` SET `content_loc4`="目标为 <NULL>" WHERE `entry`=534;
UPDATE `mangos_string` SET `content_loc4`="家移动到 (X:%f Y:%f Z:%f)" WHERE `entry`=535;
UPDATE `mangos_string` SET `content_loc4`="家移动用于玩家？" WHERE `entry`=536;
UPDATE `mangos_string` SET `content_loc4`="狮鹫飞行" WHERE `entry`=537;
UPDATE `mangos_string` SET `content_loc4`="未知的移动生成器 (%u)" WHERE `entry`=538;
UPDATE `mangos_string` SET `content_loc4`="选中的玩家: %s.\r\n阵营: %u.\r\nNPC标志: %u.\r\n输入: %u.\r\n显示ID: %u (本地: %u)." WHERE `entry`=539;
UPDATE `mangos_string` SET `content_loc4`="等级: %u。" WHERE `entry`=540;
UPDATE `mangos_string` SET `content_loc4`="健康 (基础): %u. (最大): %u. (当前): %u." WHERE `entry`=541;
UPDATE `mangos_string` SET `content_loc4`="单位旗帜: %u.\r\n电动旗帜: %u.\r\n阵营样板: %u." WHERE `entry`=542;
UPDATE `mangos_string` SET `content_loc4`="战利品: %u 扒手: %u 剥皮: %u" WHERE `entry`=543;
UPDATE `mangos_string` SET `content_loc4`="位置: %f% f%f。" WHERE `entry`=544;
UPDATE `mangos_string` SET `content_loc4`="***是一个供应商！" WHERE `entry`=545;
UPDATE `mangos_string` SET `content_loc4`="***是一名教练！" WHERE `entry`=546;
UPDATE `mangos_string` SET `content_loc4`="副本ID: %u" WHERE `entry`=547;
UPDATE `mangos_string` SET `content_loc4`="玩家%s %s (guid: %u) 账号: %s (id: %u%s) GM级别: %u 最后登录IP: %s%s 最后登录: %s 延迟时间: %ums 客户端: %s" WHERE `entry`=548;
UPDATE `mangos_string` SET `content_loc4`="游戏时间: %s 等级: %u 金钱: %ug%us%uc 金钱开销: %ug%us%uc 金钱收入: %ug%us%uc" WHERE `entry`=549;
UPDATE `mangos_string` SET `content_loc4`=".pinfo 命令不支持离线玩家的 'rep' 选项。" WHERE `entry`=550;
UPDATE `mangos_string` SET `content_loc4`="%s 已经探测完所有的区域。" WHERE `entry`=551;
UPDATE `mangos_string` SET `content_loc4`="%s 没有探测区域。" WHERE `entry`=552;
UPDATE `mangos_string` SET `content_loc4`="%s 已经为您探索了所有的区域。" WHERE `entry`=553;
UPDATE `mangos_string` SET `content_loc4`="%s 对您隐藏了所有区域。" WHERE `entry`=554;
UPDATE `mangos_string` SET `content_loc4`="启用悬停" WHERE `entry`=555;
UPDATE `mangos_string` SET `content_loc4`="禁用悬停" WHERE `entry`=556;
UPDATE `mangos_string` SET `content_loc4`="%s 将您等级提升到 (%i)" WHERE `entry`=557;
UPDATE `mangos_string` SET `content_loc4`="%s 将您的等级降低到 (%i)" WHERE `entry`=558;
UPDATE `mangos_string` SET `content_loc4`="%s 重置你的等级进程." WHERE `entry`=559;
UPDATE `mangos_string` SET `content_loc4`="该地区已确定为已勘探地区。" WHERE `entry`=560;
UPDATE `mangos_string` SET `content_loc4`="该地区已被定为未勘探地区。" WHERE `entry`=561;
UPDATE `mangos_string` SET `content_loc4`="值索引 %u 太大，无法使用 %s (统计: %u)。" WHERE `entry`=564;
UPDATE `mangos_string` SET `content_loc4`="设置 %s 字段：%u 为 uint32值：%u" WHERE `entry`=565;
UPDATE `mangos_string` SET `content_loc4`="你设置了 %s 字段：%u 为 uint32值： %u" WHERE `entry`=566;
UPDATE `mangos_string` SET `content_loc4`="设置 %s 字段：%u 为 float值：%f" WHERE `entry`=567;
UPDATE `mangos_string` SET `content_loc4`="你设置了 %s 字段：%u 为 float值： %f" WHERE `entry`=568;
UPDATE `mangos_string` SET `content_loc4`="获取 %s uint32值:[FIELD]:%u [VALUE]:%u" WHERE `entry`=569;
UPDATE `mangos_string` SET `content_loc4`="%s 有 uint32值:[FIELD]:%u [VALUE]:%u" WHERE `entry`=570;
UPDATE `mangos_string` SET `content_loc4`="获取 %s float值:[FIELD]:%u [VALUE]:%f" WHERE `entry`=571;
UPDATE `mangos_string` SET `content_loc4`="%s 有float值:[FIELD]:%u [VALUE]:%f" WHERE `entry`=572;
UPDATE `mangos_string` SET `content_loc4`="修改 %s uint32字段:%u 为总数: %i = %u (%i)" WHERE `entry`=575;
UPDATE `mangos_string` SET `content_loc4`="你修改了 %s uint32字段:%u 为总数:%i = %u (%i)" WHERE `entry`=576;
UPDATE `mangos_string` SET `content_loc4`="你现在是不可见的" WHERE `entry`=577;
UPDATE `mangos_string` SET `content_loc4`="你现在是可见的" WHERE `entry`=578;
UPDATE `mangos_string` SET `content_loc4`="选定的玩家或生物没有害者。" WHERE `entry`=579;
UPDATE `mangos_string` SET `content_loc4`="玩家 %s 学会了所有的本种族本职业的魔法，包括任何奖励的技能。" WHERE `entry`=580;
UPDATE `mangos_string` SET `content_loc4`="在游戏对象附近找到(距离%f): %u" WHERE `entry`=581;
UPDATE `mangos_string` SET `content_loc4`="清除时间: 全部:%s 保持:%s" WHERE `entry`=582;
UPDATE `mangos_string` SET `content_loc4`="没有发现事件！" WHERE `entry`=584;
UPDATE `mangos_string` SET `content_loc4`="事件不存在！" WHERE `entry`=585;
UPDATE `mangos_string` SET `content_loc4`="事件 %u: %s%s\r\n开始: %s 结束: %s 发生: %s 全程: %s\r\n下一次状态改变: %s" WHERE `entry`=586;
UPDATE `mangos_string` SET `content_loc4`="事件 %u 已经开始!" WHERE `entry`=587;
UPDATE `mangos_string` SET `content_loc4`="事件 %u 没有开始!" WHERE `entry`=588;
UPDATE `mangos_string` SET `content_loc4`="点移动到 (X:%f Y:%f Z:%f)" WHERE `entry`=589;
UPDATE `mangos_string` SET `content_loc4`="恐惧运动" WHERE `entry`=590;
UPDATE `mangos_string` SET `content_loc4`="转移运动" WHERE `entry`=591;
UPDATE `mangos_string` SET `content_loc4`="你已经学会了所有的法术: %s" WHERE `entry`=592;
UPDATE `mangos_string` SET `content_loc4`="当前禁止账户：" WHERE `entry`=593;
UPDATE `mangos_string` SET `content_loc4`="|    帐户    |   禁止格式    |   解禁止时间  |  禁止在    |   禁止理由  |" WHERE `entry`=594;
UPDATE `mangos_string` SET `content_loc4`="现在禁止了 IPs:" WHERE `entry`=595;
UPDATE `mangos_string` SET `content_loc4`="|      IP       |   禁止日期    |   解禁日期  |  禁止在    |   禁止理由  |" WHERE `entry`=596;
UPDATE `mangos_string` SET `content_loc4`="在线GM：" WHERE `entry`=597;
UPDATE `mangos_string` SET `content_loc4`="|    账户    |  GM  |" WHERE `entry`=598;
UPDATE `mangos_string` SET `content_loc4`="没有游戏管理员。" WHERE `entry`=599;
UPDATE `mangos_string` SET `content_loc4`="联盟胜利了！" WHERE `entry`=600;
UPDATE `mangos_string` SET `content_loc4`="部落胜利了！" WHERE `entry`=601;
UPDATE `mangos_string` SET `content_loc4`="战歌峡谷的战斗将在1分内钟开始" WHERE `entry`=602;
UPDATE `mangos_string` SET `content_loc4`="战歌峡谷的战斗将在30秒内开始，请做好准备！" WHERE `entry`=603;
UPDATE `mangos_string` SET `content_loc4`="战歌峡谷的战斗开始了！" WHERE `entry`=604;
UPDATE `mangos_string` SET `content_loc4`="$N夺取了部落的旗帜！" WHERE `entry`=605;
UPDATE `mangos_string` SET `content_loc4`="$N夺取了联盟的旗帜！" WHERE `entry`=606;
UPDATE `mangos_string` SET `content_loc4`="部落的旗帜被$N丢下了！" WHERE `entry`=607;
UPDATE `mangos_string` SET `content_loc4`="联盟的旗帜被$N丢下了！" WHERE `entry`=608;
UPDATE `mangos_string` SET `content_loc4`="$N归还了联盟的旗帜！" WHERE `entry`=609;
UPDATE `mangos_string` SET `content_loc4`="$N归还了部落的旗帜！" WHERE `entry`=610;
UPDATE `mangos_string` SET `content_loc4`="部落的旗帜被$N拿起了！" WHERE `entry`=611;
UPDATE `mangos_string` SET `content_loc4`="联盟的旗帜被$N拿起了！" WHERE `entry`=612;
UPDATE `mangos_string` SET `content_loc4`="旗帜被放置在了各自的基地中" WHERE `entry`=613;
UPDATE `mangos_string` SET `content_loc4`="联盟的旗帜回到了基地中" WHERE `entry`=614;
UPDATE `mangos_string` SET `content_loc4`="部落的旗帜回到了基地中" WHERE `entry`=615;
UPDATE `mangos_string` SET `content_loc4`="战场风暴之眼将在一分钟后开始。" WHERE `entry`=636;
UPDATE `mangos_string` SET `content_loc4`="战场风暴之眼将在30秒后开始。" WHERE `entry`=637;
UPDATE `mangos_string` SET `content_loc4`="战场风暴之眼已经开始了！" WHERE `entry`=638;
UPDATE `mangos_string` SET `content_loc4`="联盟" WHERE `entry`=650;
UPDATE `mangos_string` SET `content_loc4`="部落" WHERE `entry`=651;
UPDATE `mangos_string` SET `content_loc4`="马厩" WHERE `entry`=652;
UPDATE `mangos_string` SET `content_loc4`="铁匠" WHERE `entry`=653;
UPDATE `mangos_string` SET `content_loc4`="农场" WHERE `entry`=654;
UPDATE `mangos_string` SET `content_loc4`="伐木场" WHERE `entry`=655;
UPDATE `mangos_string` SET `content_loc4`="矿洞" WHERE `entry`=656;
UPDATE `mangos_string` SET `content_loc4`="%s控制了%s" WHERE `entry`=657;
UPDATE `mangos_string` SET `content_loc4`="$N成功防守了%s" WHERE `entry`=658;
UPDATE `mangos_string` SET `content_loc4`="$N突袭了%s" WHERE `entry`=659;
UPDATE `mangos_string` SET `content_loc4`="$N占领了%s！如果不采取行动, %s将在1分钟后控制它！" WHERE `entry`=660;
UPDATE `mangos_string` SET `content_loc4`="阿拉希盆地的战斗将在1分钟内开始" WHERE `entry`=661;
UPDATE `mangos_string` SET `content_loc4`="阿拉希盆地的战斗将在30秒内开始，请做好准备！" WHERE `entry`=662;
UPDATE `mangos_string` SET `content_loc4`="阿拉希盆地的战斗开始了！" WHERE `entry`=663;
UPDATE `mangos_string` SET `content_loc4`="联盟已经收集了$1776W的资源,离胜利已经不远了！" WHERE `entry`=664;
UPDATE `mangos_string` SET `content_loc4`="部落已经收集了$1777W的资源,离胜利已经不远了！" WHERE `entry`=665;
UPDATE `mangos_string` SET `content_loc4`="你在最近的 %s 战斗之后，我们努力想为你颁发一个荣誉标志却没有成功，结束后你会发现这个荣誉标志了，但不是此刻，感谢你在 %s 的战斗。" WHERE `entry`=666;
UPDATE `mangos_string` SET `content_loc4`="你必须等待%s才能再次发言" WHERE `entry`=705;
UPDATE `mangos_string` SET `content_loc4`="这个物品在装备或库存方面有问题。" WHERE `entry`=706;
UPDATE `mangos_string` SET `content_loc4`="%s现在不想被打扰: %s" WHERE `entry`=707;
UPDATE `mangos_string` SET `content_loc4`="%s现在不在电脑旁: %s" WHERE `entry`=708;
UPDATE `mangos_string` SET `content_loc4`="不要打扰" WHERE `entry`=709;
UPDATE `mangos_string` SET `content_loc4`="不在电脑旁" WHERE `entry`=710;
UPDATE `mangos_string` SET `content_loc4`="队列状态: %s (等级: %u 到 %u)\r\n排队的联盟: %u (至少需要 %u 人)\r\n排队的人群: %u (至少需要 %u 人)" WHERE `entry`=711;
UPDATE `mangos_string` SET `content_loc4`="|cffff0000[战场队列消息]:|r %s -- [%u-%u] A: %u/%u, H: %u/%u|r" WHERE `entry`=712;
UPDATE `mangos_string` SET `content_loc4`="你还没有达到战场要求的等级" WHERE `entry`=715;
UPDATE `mangos_string` SET `content_loc4`="|cffff0000[战场队列消息]:|r %s -- [%u-%u] 开始了！|r" WHERE `entry`=717;
UPDATE `mangos_string` SET `content_loc4`="你的队伍太大了，请重组后再加入。" WHERE `entry`=720;
UPDATE `mangos_string` SET `content_loc4`="你的队伍中有离线成员，请移除后再加入。" WHERE `entry`=727;
UPDATE `mangos_string` SET `content_loc4`="你的队伍中有对立阵营的玩家。不能以队伍形式加入战场。" WHERE `entry`=728;
UPDATE `mangos_string` SET `content_loc4`="你的队伍中有玩家在其它战场中。不能以队伍形式加入。" WHERE `entry`=729;
UPDATE `mangos_string` SET `content_loc4`="你的团队中已经有人在这个战场队列中。他（她）必须先退出队列才能以队伍形式加入。" WHERE `entry`=730;
UPDATE `mangos_string` SET `content_loc4`="你的团队中有战场逃亡者。不能以队伍形式加入。" WHERE `entry`=731;
UPDATE `mangos_string` SET `content_loc4`="你的团队中已经有人在3个战场队列中。不能以队伍形式加入。" WHERE `entry`=732;
UPDATE `mangos_string` SET `content_loc4`="你不能传送到战场地图" WHERE `entry`=733;
UPDATE `mangos_string` SET `content_loc4`="你不能召唤玩家到战场或竞技场地图" WHERE `entry`=734;
UPDATE `mangos_string` SET `content_loc4`="你必须在GM模式下传送到战场上的玩家。" WHERE `entry`=735;
UPDATE `mangos_string` SET `content_loc4`="你不能从另一个战场传送到另一个战场。请先离开当前战场。" WHERE `entry`=736;
UPDATE `mangos_string` SET `content_loc4`="战场设置为1v0进行调试。" WHERE `entry`=739;
UPDATE `mangos_string` SET `content_loc4`="战场设置为普通玩家计数。" WHERE `entry`=740;
UPDATE `mangos_string` SET `content_loc4`="人数不足，游戏将在%u分钟内关闭" WHERE `entry`=750;
UPDATE `mangos_string` SET `content_loc4`="人数不足，游戏将在%u秒内关闭" WHERE `entry`=751;
UPDATE `mangos_string` SET `content_loc4`="只有联盟才能用这个传送门" WHERE `entry`=752;
UPDATE `mangos_string` SET `content_loc4`="只有部落才能用这个传送门" WHERE `entry`=753;
UPDATE `mangos_string` SET `content_loc4`="%s被%s摧毁了！" WHERE `entry`=759;
UPDATE `mangos_string` SET `content_loc4`="%s遭到攻击！如果不采取行动, %s将会摧毁它！" WHERE `entry`=760;
UPDATE `mangos_string` SET `content_loc4`="%s被%s占领了！" WHERE `entry`=761;
UPDATE `mangos_string` SET `content_loc4`="%s被%s占领了！" WHERE `entry`=762;
UPDATE `mangos_string` SET `content_loc4`="%s被%s占领了！" WHERE `entry`=763;
UPDATE `mangos_string` SET `content_loc4`="%s遭到攻击！如果不采取行动，%s将会夺取它！" WHERE `entry`=764;
UPDATE `mangos_string` SET `content_loc4`="%s占领了%s！它的物资将被用于增援！" WHERE `entry`=765;
UPDATE `mangos_string` SET `content_loc4`="深铁矿洞" WHERE `entry`=766;
UPDATE `mangos_string` SET `content_loc4`="冷齿矿洞" WHERE `entry`=767;
UPDATE `mangos_string` SET `content_loc4`="雷矛急救站" WHERE `entry`=768;
UPDATE `mangos_string` SET `content_loc4`="丹巴尔达南部碉堡" WHERE `entry`=769;
UPDATE `mangos_string` SET `content_loc4`="丹巴尔达北部碉堡" WHERE `entry`=770;
UPDATE `mangos_string` SET `content_loc4`="雷矛墓地" WHERE `entry`=771;
UPDATE `mangos_string` SET `content_loc4`="冰翼碉堡" WHERE `entry`=772;
UPDATE `mangos_string` SET `content_loc4`="石炉墓地" WHERE `entry`=773;
UPDATE `mangos_string` SET `content_loc4`="石炉碉堡" WHERE `entry`=774;
UPDATE `mangos_string` SET `content_loc4`="雪落墓地" WHERE `entry`=775;
UPDATE `mangos_string` SET `content_loc4`="冰血哨塔" WHERE `entry`=776;
UPDATE `mangos_string` SET `content_loc4`="冰血墓地" WHERE `entry`=777;
UPDATE `mangos_string` SET `content_loc4`="哨塔高地" WHERE `entry`=778;
UPDATE `mangos_string` SET `content_loc4`="霜狼墓地" WHERE `entry`=779;
UPDATE `mangos_string` SET `content_loc4`="东部霜狼哨塔" WHERE `entry`=780;
UPDATE `mangos_string` SET `content_loc4`="西部霜狼哨塔" WHERE `entry`=781;
UPDATE `mangos_string` SET `content_loc4`="霜狼急救站" WHERE `entry`=782;
UPDATE `mangos_string` SET `content_loc4`="奥特兰克山谷的战斗将在1分钟后开始" WHERE `entry`=784;
UPDATE `mangos_string` SET `content_loc4`="奥特兰克山谷的战斗将在30秒后开始，请做好准备！" WHERE `entry`=785;
UPDATE `mangos_string` SET `content_loc4`="奥特兰克山谷的战斗开始了！" WHERE `entry`=786;
UPDATE `mangos_string` SET `content_loc4`="联盟的部队正在增援！" WHERE `entry`=787;
UPDATE `mangos_string` SET `content_loc4`="部落的部队正在增援！" WHERE `entry`=788;
UPDATE `mangos_string` SET `content_loc4`="霜狼将军死了！" WHERE `entry`=789;
UPDATE `mangos_string` SET `content_loc4`="雷矛将军死了！" WHERE `entry`=790;
UPDATE `mangos_string` SET `content_loc4`="你没有足够的金币" WHERE `entry`=801;
UPDATE `mangos_string` SET `content_loc4`="你没有足够的栏位" WHERE `entry`=802;
UPDATE `mangos_string` SET `content_loc4`="你的同伴没有足够的背包空间" WHERE `entry`=803;
UPDATE `mangos_string` SET `content_loc4`="您没有执行该功能的权限" WHERE `entry`=804;
UPDATE `mangos_string` SET `content_loc4`="未知语言" WHERE `entry`=805;
UPDATE `mangos_string` SET `content_loc4`="你不会这种语言" WHERE `entry`=806;
UPDATE `mangos_string` SET `content_loc4`="请提供角色名称" WHERE `entry`=807;
UPDATE `mangos_string` SET `content_loc4`="玩家%s找不到或不在线" WHERE `entry`=808;
UPDATE `mangos_string` SET `content_loc4`="未找到账户为%s的玩家" WHERE `entry`=809;
UPDATE `mangos_string` SET `content_loc4`="会长" WHERE `entry`=811;
UPDATE `mangos_string` SET `content_loc4`="官员" WHERE `entry`=812;
UPDATE `mangos_string` SET `content_loc4`="老兵" WHERE `entry`=813;
UPDATE `mangos_string` SET `content_loc4`="会员" WHERE `entry`=814;
UPDATE `mangos_string` SET `content_loc4`="新兵" WHERE `entry`=815;
UPDATE `mangos_string` SET `content_loc4`="退出守护进程..." WHERE `entry`=1000;
UPDATE `mangos_string` SET `content_loc4`="删除账号 ：%s" WHERE `entry`=1001;
UPDATE `mangos_string` SET `content_loc4`="帐户%s未删除 (可能更新了sql文件格式)" WHERE `entry`=1002;
UPDATE `mangos_string` SET `content_loc4`="帐户%s未删除 (未知错误)" WHERE `entry`=1003;
UPDATE `mangos_string` SET `content_loc4`="创建账户:%s" WHERE `entry`=1004;
UPDATE `mangos_string` SET `content_loc4`="帐号名称不能超过16个字符(客户端限制)，帐号未创建！" WHERE `entry`=1005;
UPDATE `mangos_string` SET `content_loc4`="使用此名称的帐户已经存在！" WHERE `entry`=1006;
UPDATE `mangos_string` SET `content_loc4`="帐户%s未创建 (可能更新了sql文件格式)" WHERE `entry`=1007;
UPDATE `mangos_string` SET `content_loc4`="帐户%s未创建 (未知错误)" WHERE `entry`=1008;
UPDATE `mangos_string` SET `content_loc4`="删除玩家%s (Guid: %u)帐号%s (Id: %u)。" WHERE `entry`=1009;
UPDATE `mangos_string` SET `content_loc4`="| ID         |    账户    |       角色      |       IP        | GM | 扩展 |" WHERE `entry`=1010;
UPDATE `mangos_string` SET `content_loc4`="没有在线玩家。" WHERE `entry`=1014;
UPDATE `mangos_string` SET `content_loc4`="使用未完全输入的退出命令，需要输入完整(quit)，或在RA命令行中未使用的命令。" WHERE `entry`=1015;
UPDATE `mangos_string` SET `content_loc4`="| GUID       | 名称                 | 账户                      | 删除日期         |" WHERE `entry`=1016;
UPDATE `mangos_string` SET `content_loc4`="角色未找到。" WHERE `entry`=1019;
UPDATE `mangos_string` SET `content_loc4`="恢复后的角色。" WHERE `entry`=1020;
UPDATE `mangos_string` SET `content_loc4`="删除后的角色。" WHERE `entry`=1021;
UPDATE `mangos_string` SET `content_loc4`="错误:如果您只选择了一个角色，那么您只能分配一个新名称！" WHERE `entry`=1022;
UPDATE `mangos_string` SET `content_loc4`="角色 '%s' (GUID: %u 账户 %u) 不能恢复: 账户不存在！" WHERE `entry`=1023;
UPDATE `mangos_string` SET `content_loc4`="角色 '%s' (GUID: %u 账户 %u) 不能恢复: 账户角色表已满！" WHERE `entry`=1024;
UPDATE `mangos_string` SET `content_loc4`="角色 '%s' (GUID: %u 账户 %u) 不能恢复: 已使用的新名称！" WHERE `entry`=1025;
UPDATE `mangos_string` SET `content_loc4`="GUID: %u 名称: %s 账户: %s (%u) 日期: %s" WHERE `entry`=1026;
UPDATE `mangos_string` SET `content_loc4`="日志过滤状态：" WHERE `entry`=1027;
UPDATE `mangos_string` SET `content_loc4`="所有日志过滤设置为：%s" WHERE `entry`=1028;
UPDATE `mangos_string` SET `content_loc4`="命令只能从RA控制台调用。" WHERE `entry`=1029;
UPDATE `mangos_string` SET `content_loc4`="帐户 %s (Id: %u) 现在最多允许 %u 个扩展." WHERE `entry`=1100;
UPDATE `mangos_string` SET `content_loc4`="今日消息更改为:%s" WHERE `entry`=1101;
UPDATE `mangos_string` SET `content_loc4`="发送到%s的消息:%s" WHERE `entry`=1102;
UPDATE `mangos_string` SET `content_loc4`="打开文件失败:%s" WHERE `entry`=1112;
UPDATE `mangos_string` SET `content_loc4`="帐号 %s (%u) 已经达到最大角色限制 (客户端限制)" WHERE `entry`=1113;
UPDATE `mangos_string` SET `content_loc4`="转储文件已损坏数据!" WHERE `entry`=1114;
UPDATE `mangos_string` SET `content_loc4`="无效的角色名！" WHERE `entry`=1115;
UPDATE `mangos_string` SET `content_loc4`="无效的角色公会！" WHERE `entry`=1116;
UPDATE `mangos_string` SET `content_loc4`="角色 guid %u 在使用中！" WHERE `entry`=1117;
UPDATE `mangos_string` SET `content_loc4`="您必须使用男性或女性作为性别。" WHERE `entry`=1119;
UPDATE `mangos_string` SET `content_loc4`="您将%s的性别更改为%s。" WHERE `entry`=1120;
UPDATE `mangos_string` SET `content_loc4`="您的性别由%s更改为%s。" WHERE `entry`=1121;
UPDATE `mangos_string` SET `content_loc4`="事件启动 %u \"%s\"" WHERE `entry`=1130;
UPDATE `mangos_string` SET `content_loc4`="事件停止 %u \"%s\"" WHERE `entry`=1131;
UPDATE `mangos_string` SET `content_loc4`="跟随玩家 %s (lowguid %u)" WHERE `entry`=1132;
UPDATE `mangos_string` SET `content_loc4`="跟随生物  %s (lowguid %u)" WHERE `entry`=1133;
UPDATE `mangos_string` SET `content_loc4`="跟随 <NULL>" WHERE `entry`=1134;
UPDATE `mangos_string` SET `content_loc4`="已知天赋名单：" WHERE `entry`=1135;
UPDATE `mangos_string` SET `content_loc4`="(发现天赋: %u 使用天赋点数: %u)" WHERE `entry`=1136;
UPDATE `mangos_string` SET `content_loc4`="%u - %s (在线:%s IP:%s GM:%u 扩展:%u)" WHERE `entry`=1142;
UPDATE `mangos_string` SET `content_loc4`="引发的事件 %u (%s)" WHERE `entry`=1143;
UPDATE `mangos_string` SET `content_loc4`="抛弃的事件 %u (%s)" WHERE `entry`=1144;
UPDATE `mangos_string` SET `content_loc4`="部分池 %u" WHERE `entry`=1145;
UPDATE `mangos_string` SET `content_loc4`="部分池 %u, 顶部池 %u" WHERE `entry`=1146;
UPDATE `mangos_string` SET `content_loc4`="顶部池 %u 由事件 %u (%s) 引发" WHERE `entry`=1147;
UPDATE `mangos_string` SET `content_loc4`="顶部池 %u 由事件 %u (%s) 抛弃" WHERE `entry`=1148;
UPDATE `mangos_string` SET `content_loc4`="(池 %u)" WHERE `entry`=1149;
UPDATE `mangos_string` SET `content_loc4`="(事件 %i)" WHERE `entry`=1150;
UPDATE `mangos_string` SET `content_loc4`="(池 %u 事件 %i)" WHERE `entry`=1151;
UPDATE `mangos_string` SET `content_loc4`="[可用]" WHERE `entry`=1152;
UPDATE `mangos_string` SET `content_loc4`="未找到或无法访问脚本库。" WHERE `entry`=1166;
UPDATE `mangos_string` SET `content_loc4`="脚本库有错误的功能列表 (过时？)。" WHERE `entry`=1167;
UPDATE `mangos_string` SET `content_loc4`="脚本库加载成功。" WHERE `entry`=1168;
UPDATE `mangos_string` SET `content_loc4`="为不同的mangosd版本构建脚本库。" WHERE `entry`=1169;
UPDATE `mangos_string` SET `content_loc4`="您试图查看cinemitic %u，但它并不存在。" WHERE `entry`=1200;
UPDATE `mangos_string` SET `content_loc4`="直接治疗" WHERE `entry`=1203;
UPDATE `mangos_string` SET `content_loc4`="直接伤害" WHERE `entry`=1204;
UPDATE `mangos_string` SET `content_loc4`="点治疗" WHERE `entry`=1205;
UPDATE `mangos_string` SET `content_loc4`="点伤害" WHERE `entry`=1206;
UPDATE `mangos_string` SET `content_loc4`="列兵" WHERE `entry`=1400;
UPDATE `mangos_string` SET `content_loc4`="下士" WHERE `entry`=1401;
UPDATE `mangos_string` SET `content_loc4`="中士" WHERE `entry`=1402;
UPDATE `mangos_string` SET `content_loc4`="军士长" WHERE `entry`=1403;
UPDATE `mangos_string` SET `content_loc4`="士官长" WHERE `entry`=1404;
UPDATE `mangos_string` SET `content_loc4`="骑士" WHERE `entry`=1405;
UPDATE `mangos_string` SET `content_loc4`="骑士中尉" WHERE `entry`=1406;
UPDATE `mangos_string` SET `content_loc4`="骑士队长" WHERE `entry`=1407;
UPDATE `mangos_string` SET `content_loc4`="骑士护卫" WHERE `entry`=1408;
UPDATE `mangos_string` SET `content_loc4`="少校" WHERE `entry`=1409;
UPDATE `mangos_string` SET `content_loc4`="司令" WHERE `entry`=1410;
UPDATE `mangos_string` SET `content_loc4`="统帅" WHERE `entry`=1411;
UPDATE `mangos_string` SET `content_loc4`="元帅" WHERE `entry`=1412;
UPDATE `mangos_string` SET `content_loc4`="大元帅" WHERE `entry`=1413;
UPDATE `mangos_string` SET `content_loc4`="斥侯" WHERE `entry`=1414;
UPDATE `mangos_string` SET `content_loc4`="步兵" WHERE `entry`=1415;
UPDATE `mangos_string` SET `content_loc4`="中士" WHERE `entry`=1416;
UPDATE `mangos_string` SET `content_loc4`="高阶军士" WHERE `entry`=1417;
UPDATE `mangos_string` SET `content_loc4`="一等军士长" WHERE `entry`=1418;
UPDATE `mangos_string` SET `content_loc4`="石头守卫" WHERE `entry`=1419;
UPDATE `mangos_string` SET `content_loc4`="血卫士" WHERE `entry`=1420;
UPDATE `mangos_string` SET `content_loc4`="军团士兵" WHERE `entry`=1421;
UPDATE `mangos_string` SET `content_loc4`="百夫长" WHERE `entry`=1422;
UPDATE `mangos_string` SET `content_loc4`="勇士" WHERE `entry`=1423;
UPDATE `mangos_string` SET `content_loc4`="中将" WHERE `entry`=1424;
UPDATE `mangos_string` SET `content_loc4`="将军" WHERE `entry`=1425;
UPDATE `mangos_string` SET `content_loc4`="督军" WHERE `entry`=1426;
UPDATE `mangos_string` SET `content_loc4`="高阶督军" WHERE `entry`=1427;
UPDATE `mangos_string` SET `content_loc4`="游戏管理员" WHERE `entry`=1428;
UPDATE `mangos_string` SET `content_loc4`="无军衔" WHERE `entry`=1429;
UPDATE `mangos_string` SET `content_loc4`="羞辱" WHERE `entry`=1430;
UPDATE `mangos_string` SET `content_loc4`="流亡" WHERE `entry`=1431;
UPDATE `mangos_string` SET `content_loc4`="歹徒" WHERE `entry`=1432;
UPDATE `mangos_string` SET `content_loc4`="贫民" WHERE `entry`=1433;
UPDATE `mangos_string` SET `content_loc4`="玩家:%s - %s (排名 %u)" WHERE `entry`=1434;
UPDATE `mangos_string` SET `content_loc4`="今日: [荣誉杀戮: |c0000ff00%u|r] [非荣誉杀戮: |c00ff0000%u|r]" WHERE `entry`=1435;
UPDATE `mangos_string` SET `content_loc4`="昨日: [杀戮: |c0000ff00%u|r] [荣誉: %u]" WHERE `entry`=1436;
UPDATE `mangos_string` SET `content_loc4`="本周: [杀戮: |c0000ff00%u|r] [荣誉: %u]" WHERE `entry`=1437;
UPDATE `mangos_string` SET `content_loc4`="上周: [杀戮: |c0000ff00%u|r] [荣誉: %u] [战绩: %u]" WHERE `entry`=1438;
UPDATE `mangos_string` SET `content_loc4`="使用期限: [排名: |c0000ff00%f|r] [荣誉杀戮: |c0000ff00%u|r] [非荣誉杀戮: |c00ff0000%u|r] [最高等级 %u: %s]" WHERE `entry`=1439;
UPDATE `mangos_string` SET `content_loc4`="不能添加派生，因为在保留的guid范围内没有用于静态派生的空闲guid。在使用命令之前，需要重新启动服务器。看上去需要GuidReserveSize.*配置选项。" WHERE `entry`=1503;
UPDATE `mangos_string` SET `content_loc4`="AI-信息为了Npc Entry %u" WHERE `entry`=1504;
UPDATE `mangos_string` SET `content_loc4`="AI名称: %s (%s) 脚本名称: %s" WHERE `entry`=1505;
UPDATE `mangos_string` SET `content_loc4`="当前局面 = %u" WHERE `entry`=1506;
UPDATE `mangos_string` SET `content_loc4`="运动的战斗是 %s" WHERE `entry`=1507;
UPDATE `mangos_string` SET `content_loc4`="近战攻击是 %s" WHERE `entry`=1508;
UPDATE `mangos_string` SET `content_loc4`="部落占领了北关塔！" WHERE `entry`=10033;
UPDATE `mangos_string` SET `content_loc4`="联盟占领了北关塔！" WHERE `entry`=10034;
UPDATE `mangos_string` SET `content_loc4`="部落占领了东墙塔！" WHERE `entry`=10035;
UPDATE `mangos_string` SET `content_loc4`="联盟占领了东墙塔！" WHERE `entry`=10036;
UPDATE `mangos_string` SET `content_loc4`="部落占领了守卫塔！" WHERE `entry`=10037;
UPDATE `mangos_string` SET `content_loc4`="联盟占领了守卫塔！" WHERE `entry`=10038;
UPDATE `mangos_string` SET `content_loc4`="部落占领了瘟疫之塔！" WHERE `entry`=10039;
UPDATE `mangos_string` SET `content_loc4`="联盟占领了瘟疫之塔！" WHERE `entry`=10040;
UPDATE `mangos_string` SET `content_loc4`="部落失去了北关塔！" WHERE `entry`=10041;
UPDATE `mangos_string` SET `content_loc4`="联盟失去了北关塔！" WHERE `entry`=10042;
UPDATE `mangos_string` SET `content_loc4`="部落失去了东墙塔！" WHERE `entry`=10043;
UPDATE `mangos_string` SET `content_loc4`="联盟失去了东墙塔！" WHERE `entry`=10044;
UPDATE `mangos_string` SET `content_loc4`="部落失去了皇冠卫队塔！" WHERE `entry`=10045;
UPDATE `mangos_string` SET `content_loc4`="联盟失去了皇冠卫队塔！" WHERE `entry`=10046;
UPDATE `mangos_string` SET `content_loc4`="部落失去了瘟疫之塔！" WHERE `entry`=10047;
UPDATE `mangos_string` SET `content_loc4`="联盟失去了瘟疫之塔！" WHERE `entry`=10048;
UPDATE `mangos_string` SET `content_loc4`="部落已经收集了200颗水晶！" WHERE `entry`=10049;
UPDATE `mangos_string` SET `content_loc4`="联盟已经收集了200颗水晶！" WHERE `entry`=10050;
UPDATE `mangos_string` SET `content_loc4`="带我去北地哨塔。" WHERE `entry`=10051;
UPDATE `mangos_string` SET `content_loc4`="带我去东墙哨塔。" WHERE `entry`=10052;
UPDATE `mangos_string` SET `content_loc4`="链接ID: %u" WHERE `entry`=11010;
UPDATE `mangos_string` SET `content_loc4`="加入英语社区频道(/join WorldEN)与所有玩家一起交流！" WHERE `entry`=11011;
UPDATE `mangos_string` SET `content_loc4`="命令 \".go warsong\", \".go arathi\" 和 \".go alterac\" 帮助您加入战场从任何地方！" WHERE `entry`=11012;
UPDATE `mangos_string` SET `content_loc4`="为了帮助服务器人口增长，启动招聘驱动！NPC 60 可用，角色从其他服务器导入可用，订阅我们的Facebook ！" WHERE `entry`=11013;
UPDATE `mangos_string` SET `content_loc4`="服务器将关闭 19/08 国际版，更多信息在论坛查看。" WHERE `entry`=11014;
UPDATE `mangos_string` SET `content_loc4`="我想浏览一下你们的商品。" WHERE `entry`=2000;
UPDATE `mangos_string` SET `content_loc4`="小芒果魔兽是一个PVP & PVE服务器。然而，那些试图搞破坏的玩家将会受到惩罚。" WHERE `entry`=11015;
UPDATE `mangos_string` SET `content_loc4`="赏金猎人系统可用，请联系GM给你的保留价格的人，更多活动信息在论坛查看。" WHERE `entry`=11016;
UPDATE `mangos_string` SET `content_loc4`="跟着我！" WHERE `entry`=2001;
UPDATE `mangos_string` SET `content_loc4`="%s 试图在恐惧中逃跑！" WHERE `entry`=5030;
UPDATE `mangos_string` SET `content_loc4`="Snivvle在这里! Snivvle 声称这颗冰冷的牙齿属于我！" WHERE `entry`=791;
UPDATE `mangos_string` SET `content_loc4`="现在是时候进攻了！ 为了部落！" WHERE `entry`=792;
UPDATE `mangos_string` SET `content_loc4`="振作起来，联盟！把这些坏蛋从奥特兰克山谷赶出去！" WHERE `entry`=793;
UPDATE `mangos_string` SET `content_loc4`="%s %s%s %s (guid: %u) 账户: %s (id: %u%s) GM级别: %u 最后登录IP: %s%s 最后登录: %s 延迟: %ums 客户端: %s 2FA: %s" WHERE `entry`=616;
UPDATE `mangos_string` SET `content_loc4`="票未找到。" WHERE `entry`=2005;
UPDATE `mangos_string` SET `content_loc4`="请在永久删除之前关闭入场券。" WHERE `entry`=2006;
UPDATE `mangos_string` SET `content_loc4`="入场券%d已经分配。" WHERE `entry`=2007;
UPDATE `mangos_string` SET `content_loc4`="%u入场券成功地从数据库重新加载。" WHERE `entry`=2008;
UPDATE `mangos_string` SET `content_loc4`="显示开放的入场券名单。" WHERE `entry`=2009;
UPDATE `mangos_string` SET `content_loc4`="显示其创建者在线的开放入场券列表。" WHERE `entry`=2010;
UPDATE `mangos_string` SET `content_loc4`="显示已关闭的入场券名单。" WHERE `entry`=2011;
UPDATE `mangos_string` SET `content_loc4`="指定的名字无效。名字应该是一个在线游戏管理员的名字。" WHERE `entry`=2012;
UPDATE `mangos_string` SET `content_loc4`="这张入场券已经给你了。使用 .ticket 命令取消分配 %d，然后重新分配。" WHERE `entry`=2013;
UPDATE `mangos_string` SET `content_loc4`="%d入场券没有分配，不能取消分配。" WHERE `entry`=2014;
UPDATE `mangos_string` SET `content_loc4`="您不能从具有比您更高安全级别的工作人员处取消分配入场券。" WHERE `entry`=2015;
UPDATE `mangos_string` SET `content_loc4`="无法关闭票%d，它被分配给另一个GM。" WHERE `entry`=2016;
UPDATE `mangos_string` SET `content_loc4`="有待开放的门票，请先关闭它们！" WHERE `entry`=2027;
UPDATE `mangos_string` SET `content_loc4`="所有已关闭的票已被删除，计数器被重新设置为|cffff00ff 1|r" WHERE `entry`=2028;
UPDATE `mangos_string` SET `content_loc4`="票现在被禁用" WHERE `entry`=2031;
UPDATE `mangos_string` SET `content_loc4`="现在可以买票了" WHERE `entry`=2040;
UPDATE `mangos_string` SET `content_loc4`="票现在被禁用" WHERE `entry`=2041;
UPDATE `mangos_string` SET `content_loc4`="已重新设置入场券%s的响应。" WHERE `entry`=2042;
UPDATE `mangos_string` SET `content_loc4`="此票已存档(已完成或已关闭)。" WHERE `entry`=2043;
UPDATE `mangos_string` SET `content_loc4`="这张票已经分配给别人了。未分配第一。" WHERE `entry`=2044;
UPDATE `mangos_string` SET `content_loc4`="票#%u添加到升级列表。" WHERE `entry`=2045;
UPDATE `mangos_string` SET `content_loc4`="升级列表中的票:" WHERE `entry`=2026;
UPDATE `mangos_string` SET `content_loc4`="%s: 等级 %u" WHERE `entry`=2046;
UPDATE `mangos_string` SET `content_loc4`="这张票已经买好了。请打开一个新的。" WHERE `entry`=2047;
UPDATE `mangos_string` SET `content_loc4`="您的入场券已被编辑并回复。" WHERE `entry`=2048;
UPDATE `mangos_string` SET `content_loc4`="通用售票处设置为入场券#%u" WHERE `entry`=2051;
UPDATE `mangos_string` SET `content_loc4`="出现在 %s 的位置 (离线)。" WHERE `entry`=176;
UPDATE `mangos_string` SET `content_loc4`="%s 复活 (在线)" WHERE `entry`=5031;
UPDATE `mangos_string` SET `content_loc4`="%s 复活 (离线)" WHERE `entry`=5032;
UPDATE `mangos_string` SET `content_loc4`="|cffffff00北地哨塔被部落占领了！|r" WHERE `entry`=1600;
UPDATE `mangos_string` SET `content_loc4`="|cffffff00北地哨塔被联盟占领了！|r" WHERE `entry`=1601;
UPDATE `mangos_string` SET `content_loc4`="|cffffff00皇冠哨塔被部落占领了！|r" WHERE `entry`=1602;
UPDATE `mangos_string` SET `content_loc4`="|cffffff00皇冠哨塔被联盟占领了！|r" WHERE `entry`=1603;
UPDATE `mangos_string` SET `content_loc4`="队伍类型: %s (ID: %s) 领袖: %s 玩家统计: %d 所有玩家: %s" WHERE `entry`=640;
UPDATE `mangos_string` SET `content_loc4`="隐身模式开启" WHERE `entry`=345;
UPDATE `mangos_string` SET `content_loc4`="隐身模式关闭" WHERE `entry`=346;
UPDATE `mangos_string` SET `content_loc4`="上帝模式开启" WHERE `entry`=349;
UPDATE `mangos_string` SET `content_loc4`="上帝模式关闭" WHERE `entry`=350;
UPDATE `mangos_string` SET `content_loc4`="票通知启用。" WHERE `entry`=2049;
UPDATE `mangos_string` SET `content_loc4`="票通知禁用。" WHERE `entry`=2050;
UPDATE `mangos_string` SET `content_loc4`="您将%s的力量更改为%i。" WHERE `entry`=900;
UPDATE `mangos_string` SET `content_loc4`="%s将您的力量更改为%i。" WHERE `entry`=901;
UPDATE `mangos_string` SET `content_loc4`="您将%s的敏捷更改为%i。" WHERE `entry`=902;
UPDATE `mangos_string` SET `content_loc4`="%s将您的敏捷更改为%i。" WHERE `entry`=903;
UPDATE `mangos_string` SET `content_loc4`="您将%s的耐力更改为%i。" WHERE `entry`=904;
UPDATE `mangos_string` SET `content_loc4`="%s将您的耐力更改为%i。" WHERE `entry`=905;
UPDATE `mangos_string` SET `content_loc4`="您将%s的智力更改为%i。" WHERE `entry`=906;
UPDATE `mangos_string` SET `content_loc4`="%s将您的智力更改为%i。" WHERE `entry`=907;
UPDATE `mangos_string` SET `content_loc4`="您将%s的精神更改为%i。" WHERE `entry`=908;
UPDATE `mangos_string` SET `content_loc4`="%s将您的精神更改为%i。" WHERE `entry`=909;
UPDATE `mangos_string` SET `content_loc4`="您将%s的防御力更改为%i。" WHERE `entry`=910;
UPDATE `mangos_string` SET `content_loc4`="%s将您的防御力更改为%i。" WHERE `entry`=911;
UPDATE `mangos_string` SET `content_loc4`="您将%s的神圣抗性更改为%i。" WHERE `entry`=912;
UPDATE `mangos_string` SET `content_loc4`="%s将您的神圣抗性更改为%i。" WHERE `entry`=913;
UPDATE `mangos_string` SET `content_loc4`="您将%s的火焰抗性更改为%i。" WHERE `entry`=914;
UPDATE `mangos_string` SET `content_loc4`="%s将您的火焰抗性更改为%i。" WHERE `entry`=915;
UPDATE `mangos_string` SET `content_loc4`="您将%s的自然抗性更改为%i。" WHERE `entry`=916;
UPDATE `mangos_string` SET `content_loc4`="%s将您的自然抗性更改为%i。" WHERE `entry`=917;
UPDATE `mangos_string` SET `content_loc4`="您将%s的冰霜抗性更改为%i。" WHERE `entry`=918;
UPDATE `mangos_string` SET `content_loc4`="%s将您的冰霜抗性更改为%i。" WHERE `entry`=919;
UPDATE `mangos_string` SET `content_loc4`="您将%s的暗影抗性更改为%i。" WHERE `entry`=920;
UPDATE `mangos_string` SET `content_loc4`="%s将您的暗影抗性更改为%i。" WHERE `entry`=921;
UPDATE `mangos_string` SET `content_loc4`="您将%s的奥数抗性更改为%i。" WHERE `entry`=922;
UPDATE `mangos_string` SET `content_loc4`="%s将您的奥数抗性更改为%i。" WHERE `entry`=923;
UPDATE `mangos_string` SET `content_loc4`="您将%s的近战伤害更改为%i。" WHERE `entry`=924;
UPDATE `mangos_string` SET `content_loc4`="%s将您的近战伤害更改为%i。" WHERE `entry`=925;
UPDATE `mangos_string` SET `content_loc4`="您将%s的远程伤害更改为%i。" WHERE `entry`=926;
UPDATE `mangos_string` SET `content_loc4`="%s将您的远程伤害更改为%i。" WHERE `entry`=927;
UPDATE `mangos_string` SET `content_loc4`="您将%s的法术能量更改为%i。" WHERE `entry`=928;
UPDATE `mangos_string` SET `content_loc4`="%s将您的法术能量更改为%i。" WHERE `entry`=929;
UPDATE `mangos_string` SET `content_loc4`="您将%s的近战暴击更改为%g%%。" WHERE `entry`=930;
UPDATE `mangos_string` SET `content_loc4`="%s将您的近战暴击更改为%g%%。" WHERE `entry`=931;
UPDATE `mangos_string` SET `content_loc4`="您将%s的射程暴击更改为%g%%。" WHERE `entry`=932;
UPDATE `mangos_string` SET `content_loc4`="%s将您的射程暴击更改为%g%%。" WHERE `entry`=933;
UPDATE `mangos_string` SET `content_loc4`="您将%s的法术暴击更改为%g%%。" WHERE `entry`=934;
UPDATE `mangos_string` SET `content_loc4`="%s将您的法术暴击更改为%g%%。" WHERE `entry`=935;
UPDATE `mangos_string` SET `content_loc4`="您将%s的主手速度更改为%i ms。" WHERE `entry`=936;
UPDATE `mangos_string` SET `content_loc4`="%s将您的主手速度更改为%i ms。" WHERE `entry`=937;
UPDATE `mangos_string` SET `content_loc4`="您将%s的副手速度更改为%i ms。" WHERE `entry`=938;
UPDATE `mangos_string` SET `content_loc4`="%s将您的副手速度更改为%i ms。" WHERE `entry`=939;
UPDATE `mangos_string` SET `content_loc4`="您将%s的远程速度更改为%i ms。" WHERE `entry`=940;
UPDATE `mangos_string` SET `content_loc4`="%s将您的远程速度更改为%i ms。" WHERE `entry`=941;
UPDATE `mangos_string` SET `content_loc4`="您将%s的锻造速度更改为%gx。" WHERE `entry`=942;
UPDATE `mangos_string` SET `content_loc4`="%s将您的锻造速度更改为%gx。" WHERE `entry`=943;
UPDATE `mangos_string` SET `content_loc4`="您将%s的格挡机率更改为%g%%。" WHERE `entry`=944;
UPDATE `mangos_string` SET `content_loc4`="%s将您的格挡机率更改为%g%%。" WHERE `entry`=945;
UPDATE `mangos_string` SET `content_loc4`="您将%s的躲闪机率更改为%g%%。" WHERE `entry`=946;
UPDATE `mangos_string` SET `content_loc4`="%s将您的躲闪机率更改为%g%%。" WHERE `entry`=947;
UPDATE `mangos_string` SET `content_loc4`="您将%s的招架机率更改为%g%%。" WHERE `entry`=948;
UPDATE `mangos_string` SET `content_loc4`="%s将您的招架机率更改为%g%%。" WHERE `entry`=949;
UPDATE `mangos_string` SET `content_loc4`="找不到公会。" WHERE `entry`=562;
UPDATE `mangos_string` SET `content_loc4`="试图邀请玩家加入公会时发生错误。" WHERE `entry`=563;
UPDATE `mangos_string` SET `content_loc4`="锁定账户字段 %s (id %u) 更改为 %u." WHERE `entry`=1170;
UPDATE `mangos_string` SET `content_loc4`="参数错误. 用法:\r\n.account set locked <账户> <值>\r\n锁定类型：0 None, 1 IP, 2 PIN, 4 TOTP, 8 Enforce" WHERE `entry`=1171;
UPDATE `mangos_string` SET `content_loc4`="无效的骑行类型。 请尝试以下方法之一：\r\n%s" WHERE `entry`=1172;
UPDATE `mangos_string` SET `content_loc4`="那个玩家没有 %s 的骑术。" WHERE `entry`=1173;
UPDATE `mangos_string` SET `content_loc4`="试图移除骑术时遇到错误。" WHERE `entry`=1174;
UPDATE `mangos_string` SET `content_loc4`="骑术技能从玩家 %s 中移除。" WHERE `entry`=1175;
UPDATE `mangos_string` SET `content_loc4`="你必须是部落成员才能进入" WHERE `entry`=67;
UPDATE `mangos_string` SET `content_loc4`="你必须是联盟成员才能进入" WHERE `entry`=68;
UPDATE `mangos_string` SET `content_loc4`="你必须在%u级以下才能进入" WHERE `entry`=69;
UPDATE `mangos_string` SET `content_loc4`="活动对象t: %d. 可见修改: %0.2f" WHERE `entry`=1030;
UPDATE `mangos_string` SET `content_loc4`="亲爱的玩家,\r\n\r\n请接受信中所附的物品。早些时候它从你的角色中移除，因为它不应该在当前的补丁中可用，但是我们的技术人员已经得出结论，你现在可以把它拿回来了！\r\n\r\n小芒果QQ群：491767664" WHERE `entry`=699;
UPDATE `mangos_string` SET `content_loc4`="设备ID:  %u" WHERE `entry`=1031;
UPDATE `mangos_string` SET `content_loc4`="居住类型: %u" WHERE `entry`=1032;
UPDATE `mangos_string` SET `content_loc4`="护甲: %u" WHERE `entry`=1033;
UPDATE `mangos_string` SET `content_loc4`="AI名称: %s 脚本名称: %s" WHERE `entry`=1034;
UPDATE `mangos_string` SET `content_loc4`="法力 (基础): %u. (最大): %u. (当前): %u." WHERE `entry`=11017;
UPDATE `mangos_string` SET `content_loc4`="没有声音。" WHERE `entry`=617;
UPDATE `mangos_string` SET `content_loc4`="没有发现生物模型！" WHERE `entry`=1177;
UPDATE `mangos_string` SET `content_loc4`="您将%s的狮鹫飞行速度从正常设置为 %2.2f。" WHERE `entry`=145;
UPDATE `mangos_string` SET `content_loc4`="%s将您的狮鹫飞行速度从正常设置为%2.2f。" WHERE `entry`=146;
UPDATE `mangos_string` SET `content_loc4`="你发现了你所在阵营的所有飞行点。" WHERE `entry`=453;
UPDATE `mangos_string` SET `content_loc4`="你必须达到%u级才能进入" WHERE `entry`=70;
UPDATE `mangos_string` SET `content_loc4`="运动类型 = %u" WHERE `entry`=1509;
UPDATE `mangos_string` SET `content_loc4`="您不能将XP速率设置为低于%g！" WHERE `entry`=177;
UPDATE `mangos_string` SET `content_loc4`="您不能将XP速率设置为%g以上！" WHERE `entry`=178;
UPDATE `mangos_string` SET `content_loc4`="您已将%s的XP率更改为正常体验增益的%g倍。" WHERE `entry`=179;
