-- VMaNGOS Database Chinese script
-- Author: Mr.huang (QQ: 654706160)
-- Create time: 2019-07-11 16:12:39
-- File name: quest_greeting.sql
-- Table name: quest_greeting

USE `mangos`;
SET NAMES 'utf-8';

UPDATE `quest_greeting` SET `content_loc4`="你好，$c。 通常情况下，我会照看暴风城的民众，但很多暴风城的守卫都在其他地方作战。 因此，在我宁愿巡逻时在这里代理并提供赏金..." WHERE `entry`=823 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="嘿，朋友。我的名字叫雷米，从赤脊山的东边来的，到这里来做生意。 你想跟我做买卖吗？" WHERE `entry`=241 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="你好，朋友。你看起来像$g，你和暴风城军队有业务往来吗？" WHERE `entry`=261 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="这些地方除了麻烦什么也没有。我想告诉那个傻小子萨尔丁趁他还能出去的时候出去，可他就是不听。但我不是傻瓜。维娜和我一修好这辆车就出去闲逛。" WHERE `entry`=237 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="一场肮脏的腐败已经蔓延到了西部。当我在洛丹伦的战场上执行我的职责时，这些诚实的农场被侵占，成为暴徒和杀人犯的藏身之所。人民民兵需要你的帮助。" WHERE `entry`=234 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="你们将会受到围绕我们土地的黑暗的多次考验，$N。但为了确保你时刻做好准备，我们会经常要求你完成任务，这样你就处于自己权力的巅峰。与光同行，保持美德。" WHERE `entry`=6171 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="你好,$c ！打猎的好天气，你说呢？我自己对公猪也有不少运气。也许你想喝一杯？" WHERE `entry`=714 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="腐败潜入大自然的丛林。必须不惜一切代价保护森林。" WHERE `entry`=2930 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="黑暗势力侵入我们的边界，古老的污点重新浮现，新的邪恶出现，颠覆了这片土地微妙的平衡。在这样的黑暗时刻，我们都必须保持警惕。" WHERE `entry`=3649 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="风向倾听的人低语...你听到了吗?" WHERE `entry`=3616 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="我希望这段历史不会再次困扰我们。" WHERE `entry`=3845 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="我知道你对我印象深刻，但情况会越来越好...我很快就会告诉你更多的。" WHERE `entry`=4077 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="为了我们人类的生存，我们必须研究自然的方式和它的秘密。" WHERE `entry`=3419 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="有时候，我觉得天空中有一大片灰色的云，就像一场恶运降临在我们身上。首先，我们被赶出了我们的土地，现在我们甚至不能离开韦斯特福尔。一切都一团糟。需要做点什么。" WHERE `entry`=238 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="欢迎光临寒舍！看到一张友好的脸总是很高兴。你有多强壮的胳膊啊。我丈夫和我总是在农场周围找人帮忙。现在大多数好人都离开了，很难找到一个有能力的人来帮忙。" WHERE `entry`=235 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="黑暗女王提出了挑战。这是由我们来满足它。" WHERE `entry`=1518 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="从各方面考虑，我希望你一切都好。\r\n\r\n坐一会儿，听听我的故事。这当然是个悲剧，但我希望以复仇告终！" WHERE `entry`=1500 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="红色十字军正在侵占我们的家园。愚蠢的狂热者没有意识到黑夫人的忠实仆人们将会看到他们的死亡。" WHERE `entry`=1515 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="啊，你在那里！我有任务要做，我不需要浪费时间来解释它们的关键性质。" WHERE `entry`=1499 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="问候：$C。向东走时要时刻小心。最近的监测报告显示，该地区天灾活动有所增加，因此要谨慎行事。" WHERE `entry`=1495 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="有件事你想和我谈谈，$c... 来，坐在我旁边。" WHERE `entry`=3188 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="欢迎你回来，$n。" WHERE `entry`=5887 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="兽人语：$c。时间不多，要做的工作很多。" WHERE `entry`=3139 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="你好！Spirits说你是来帮助我的长官。大声说出来，他们会的。" WHERE `entry`=2519 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="土地、水和天空是一体的。是你的眼睛用这样的分离欺骗了你。地球母亲就是所有一切，甚至更多。" WHERE `entry`=3338 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="好吧，如果这不是一个年轻的，$c，毫无疑问是我在战场上的丰功伟绩吸引到这里来的！现在没有时间讲故事了，因为有许多伟大而重要的事情需要去做!所以如果你在寻找荣耀，那么今天好运会护佑着你..." WHERE `entry`=1343 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="是的，是的，是的！你就是我要找的$r！\r\n\r\n坐！我们有很多事情要讨论！！" WHERE `entry`=3446 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="有什么我能帮你的吗，$n？有批货我得处理一下，否则的话我可以帮你。" WHERE `entry`=3453 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="啊哈！您好，$C主人！来，坐下来喝一杯。你的眼神很有进取心，我想你会发现和我谈话很值得..." WHERE `entry`=253 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="嗯,你好。你好像不反对做一些硬币，嗯?我能从你的眼神中看出。我是摩尔·凯博克，艾泽拉斯的监工，如果你想发财，也许我能帮你安排。" WHERE `entry`=737 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="嗯，你好。我能从你的眼神中看出来，你好像不反对做一些硬币？如果你想发财，也许我能帮你安排，我是摩尔·凯博克，艾泽拉斯的监工。" WHERE `entry`=773 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="你好，$G 小伙子 : 小姑娘。我是精灵老人。我来这里是为了研究寒脊谷巨魔数量的增加所带来的威胁。我发现了什么？这有点麻烦..." WHERE `entry`=786 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="该死的联盟啤酒商！他们可以得到所有最好的原料，而我们却被困在这里挖谷物和啤酒花！" WHERE `entry`=1374 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="黑暗女王提出了挑战。现在轮到英国皇家药剂师协会来研究一种新的瘟疫。我们将让阿尔萨斯和他的军队屈服。" WHERE `entry`=1937 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="这个大锅里翻腾着厚厚的绿色气泡。未知生物的头骨、骨骼和器官在粘稠的肉汤中游动...慢慢浮出水面的是两个曾经强大的巨魔的头骨:$B$BGan'zulah和Nezzliok。" WHERE `entry`=2076 AND `type`=1;
UPDATE `quest_greeting` SET `content_loc4`="信息：通过我们的侦察兵和特工，我们控制着洛丹伦的信息流动。天灾军团的行动，他们的势力，都在我们的眼皮底下..." WHERE `entry`=2121 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="我家拥有暴风城所有贵族中最精美的珠宝和艺术品!我们一直希望扩大我们的收藏规模。" WHERE `entry`=2285 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="什么? 什么? 我们都有利润做...我们不会袖手旁观。" WHERE `entry`=2498 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="你能来真是太好了，$c。我的名字叫Lotwil Veriatus，是考古学、炼金术和工程学开明大会的创始成员：我们致力于将艾泽拉斯的智能科学融合成一所综合性的学校。" WHERE `entry`=2921 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="萨尔给我和我的孩子们丰厚的报酬，因为他们帮助建造了奥格瑞玛，所以我决定在这里建一个港口。我们的大部分业务是通过Booty Bay和Baron Revilgaz完成的。" WHERE `entry`=3391 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="我们也许没有与联盟展开公开的战争，但我们之间仍在流血。" WHERE `entry`=4791 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="如果我们想在这个世界上占有一席之地，那么我们就必须通过学习，通过无视我们日渐衰退的人类本能的意志来实现这一点。" WHERE `entry`=5204 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="别让高温打扰你。在荒地，高温是你最不需要担心的。\r\n" WHERE `entry`=5394 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="这个猪圈有点不舒服，但它有历史，所以斯通纳德对某些人来说一定很重要。我敢打赌，这就是我们留在这里的原因。当然不是为了看风景——它看起来甚至不像家。" WHERE `entry`=5591 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="我叫Bilgewhizzle，是Gadgetzan水务公司的总工程师。我能为您做些什么?" WHERE `entry`=7407 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="有些人想知道我们在沙漠里做什么。嗯...如果我告诉你，你就留下来，为我们赚钱！" WHERE `entry`=7876 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="我们是来盈利的。而且我们的货物被偷了根本就赚不到钱。" WHERE `entry`=7882 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="你好，$N。也许你有时间聊天？" WHERE `entry`=7900 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="亲爱的 $g 男孩 : 女孩，你来的正是时候，可以帮助卡加斯远征军。" WHERE `entry`=9078 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="我再也不觉得暖和了..." WHERE `entry`=10926 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="问候：$N，我是银色黎明的尼古拉斯·兹韦伦霍夫公爵。" WHERE `entry`=11039 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="嗨，$n。欢迎来到我简陋的花园。最近天气一直很好。让我们希望它能稳定下来，等待一个成熟的收成。" WHERE `entry`=342 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="啊，就算没有这些新麻烦不断的冒出来，维持这儿的秩序就已经够让人头痛的了！希望你有好消息，$n……" WHERE `entry`=240 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="为了服务于黑暗女王希尔瓦娜斯，我们需要在人类侵扰的前线向前推进。" WHERE `entry`=2215 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="我们离发展新的瘟疫如此之近，以至于我们的黑暗女王如此热切地渴望着。" WHERE `entry`=2216 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="$c。如果你只是路过，我建议你坚持走大路，只在白天出行。如果你的目的地在夜色镇，考虑把你的能力借给守夜人。我们的技术毋庸置疑，但我们的人数很少。" WHERE `entry`=264 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="赤脊山一片混乱！" WHERE `entry`=344 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="不要惊慌，$r。我早已离开这片土地，但我无意伤害你的族人。我目睹了太多的死亡。我现在唯一的愿望就是和平。也许你能帮助我的事业。" WHERE `entry`=392 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="你为什么要到湖畔镇和尊敬的所罗门镇长面前来?" WHERE `entry`=900 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="泰达希尔的创立是一项伟大的成就，但现在世界必须改变以恢复平衡。" WHERE `entry`=2080 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="斧头的重量，盟军的战斗，你脸上的血溅。这些是战士们所渴望的，我将以部落的名义用我的剑去开拓荒地。" WHERE `entry`=3337 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="这最好是好的…" WHERE `entry`=3339 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="桶子里装着各种各样的物质，我们洛丹伦的药剂师可能会用到这些物质。" WHERE `entry`=3390 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="我，阿瑞尼亚·碎云，肩负着保护神谕林圣洁的重任。" WHERE `entry`=3519 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="好了，$n。很高兴看到像你这样的人正积极参与保护森林。" WHERE `entry`=3567 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="灰谷是一片郁郁葱葱的森林，充满了生机。沿着它的秘密道路寻找草药是一种乐趣，但你必须小心。森林并非没有危险。" WHERE `entry`=3847 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="不安的亡魂！" WHERE `entry`=3995 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="石爪的灵魂在哭泣...它从它的山峰，它的河流，它的断枝，垂死的树木哭泣。" WHERE `entry`=4049 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="我们唯一的希望是在已经很糟糕的情况下创造一些好的东西。" WHERE `entry`=5767 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="多亏了酋长，即使在这里，在我们以前的监狱废墟中，仍有一些希望，部落重新崛起。" WHERE `entry`=2706 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="你在这片荒地上游荡一定很辛苦吧， $c。像我一样贫困。也许你在这里是因为你疯了。疯了,像我一样。" WHERE `entry`=2817 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="你必须听着，年轻的$c。你们要在黑暗中侧耳听那声音，因为在患难的时候，那声音能引导人。" WHERE `entry`=4046 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="靠近一点。我们有重要的事情要讨论，你和我。其中一些我们不想让每个人都听到..." WHERE `entry`=4452 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="问候：$c" WHERE `entry`=4498 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="半人马部落统治着荒漠之地。如果团结起来，他们将是一支可怕的力量。因此，半人马部落不团结反而互相争吵和战争是件好事。" WHERE `entry`=5412 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="萨尔希望处理的主要威胁是燃烧之刃 - 部落成员，他们忠于恶魔。 他们寻求练习他们的黑暗魔法，并且很少关心萨尔对卡利姆多部落未来的看法。" WHERE `entry`=5641 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="我们无法单独处理这一领域的所有威胁。 我们可以使用另一个战斗手，$n。" WHERE `entry`=10537 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="我们在战斗中度过了许多生命，和平时代的记忆越来越遥远。" WHERE `entry`=1776 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="我哥哥和我正在进行侦察任务，但是我们被困在这个农舍里。 Deathstalkers需要你的帮助！" WHERE `entry`=1950 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="要捕杀野兽，必须知道那只野兽。我们必须学习并尊重它的方式。否则，就别去打猎。无异于杀人。" WHERE `entry`=3441 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="这些日子越来越长，这些土地的冲突仍然无止境。 知道那么多并不需要施法者。 尽可能拿起刀片，$c。 战争可以随时来到我们家门口，如果我没有弄错的话，你会看起来像是一个狂热的人。" WHERE `entry`=4485 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="挑战莫格穆洛克。你照我说的做。" WHERE `entry`=4500 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="我叫Dran Droffers，这就是我的儿子Malton。 如果您需要打捞，那么我们就是您要找的人！" WHERE `entry`=6986 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="对财富的追求是一个受人尊敬的地精的唯一目标。也许是财富...，也许是死亡！" WHERE `entry`=9536 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="嗯？ 你和Nimboya有业务往来？" WHERE `entry`=2497 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="丛林中的另一个美好的一天！ 这将是一次非常有意义的狩猎，我能感受到它。 一旦巴尼尔完成清洁枪支，我就把狩猎队伍带到了扭曲的葡萄藤深处。\r\n\r\n 对于一位退休的老人而言，这并不是一种糟糕的方式，呃？" WHERE `entry`=715 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="喔！ 你在这里玩指关节游戏？" WHERE `entry`=2501 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="你怎么问我？" WHERE `entry`=5598 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="小心你把你的那只脚放在哪里，先生:女士; 我们并不都非常喜欢$R的高度。" WHERE `entry`=4453 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="你最好别浪费我的时间，伙计！" WHERE `entry`=2546 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="如果我们要保护自然，那么我们必须拥抱它的力量。我们必须向那些想要伤害这片土地的人展示我们的力量。" WHERE `entry`=5770 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="我早就感觉到你来了，$n。它是用星星的图案写的。" WHERE `entry`=265 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="关上门，$c。永远不知道黑暗骑士什么时候会再经过。" WHERE `entry`=273 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="你看看你走过的地方，$Glad:lass;。你可能不是我们服装的一部分，但这并不意味着如果你不守规矩，我就不拿拐杖打你!" WHERE `entry`=733 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="如果Rhag告诉我的一件事是没有任何任务的。 保护萨多尔大桥应该是一件容易的事。 但随着军队与联盟并肩作战，我们在这里不知所措，邓莫德已经倒下了。" WHERE `entry`=1071 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="我希望你是来工作的，$C。我们有很多事要做，部落、辛迪加和食人魔都帮不了我们。" WHERE `entry`=2263 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="当我第一次被授予南郡治安官的头衔时，我很荣幸在我职业生涯的早期就赢得了这样一个任务。但是现在我来了，我在想如果我在暴风城把文件拖来拖去是不是会更好。" WHERE `entry`=2276 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="我们在避难谷占据了阿拉希高地少数几片激流带领土之一。 而且我们正在失势... $B$B如果你有话语，那么我希望他们是好人。" WHERE `entry`=2700 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="这块木板上放着制作粗糙的通缉令。" WHERE `entry`=2713 AND `type`=1;
UPDATE `quest_greeting` SET `content_loc4`="嗨，$c。 在我这些年里，我见过很多渴望向部落证明自己价值的牛头人。不应忘记，渴望不能代替智慧和经验。" WHERE `entry`=2981 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="信使奥拉莉恩的责任是确保那些穿越莫高雷平原的人的安全。那些威胁到牛头人家园安全的人有被我们惩罚的危险。" WHERE `entry`=2988 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="这块地对我们的人民很好，$c。我们必须感谢我们的好运气。" WHERE `entry`=2993 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="在塞拉摩岛做研究是一份很有趣的工作，但是在这个城市要找到一张柔软的床肯定很难！" WHERE `entry`=4794 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="这个卷轴集包含各种后勤和战略信息，以及编码的对应关系。" WHERE `entry`=186420 AND `type`=1;
UPDATE `quest_greeting` SET `content_loc4`="从远处和附近的土地冒险$bMeeting遇到奇怪的人们但是如果我有问题你要问$bBut你必须先完成一个简单的任务！" WHERE `entry`=239 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="欢迎来到夜色镇。 书记员达尔塔为您服务。 我可以得到一些帮助吗？" WHERE `entry`=267 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="你好！欢迎来到我的厨房，$g 先生:女士;！ 这里是所有血鸦旅店最好的美食。啊，闻到美妙的香气！" WHERE `entry`=272 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="你好，$g 女士:先生;。 如果你饿了，就坐下来吃饭。 如果我看起来忙着我的针线活，请不要担心 - 我在听你..." WHERE `entry`=278 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="你看起来不像迪菲亚小偷...或是守夜人。 你会怜悯一个可怜的灵魂吗？" WHERE `entry`=288 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="问候： 年轻的$C。你是一个勇敢的人，可以在这里与所有那些流浪的生物一起找到你的方式！$B$BWell既然你在这里，也许你可以帮助一个古老的隐士..." WHERE `entry`=289 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="嗨，旅行者。我的视力可能很差，但我可以感觉到距离一英里远的$c的脚步声。 多年来，我一直以为维护暴风城引以为荣，但一旦我的眼睛失明，我就只能被迫退休。" WHERE `entry`=294 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="欢迎来到阿祖拉之塔，年轻$C。 我是Theocritus。$B$B你跟我有生意吗？ 也许我和你可以做点买卖？" WHERE `entry`=313 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="我没有多少时间闲聊，$N。我必须在下雨前把这座桥修好。我按时完成了每个项目，而且没有超出预算，我现在不打算开始走下坡路。" WHERE `entry`=341 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="好了，$C。如果你是来这里出差的，那就自己去喝杯啤酒，我们好好谈谈。" WHERE `entry`=381 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="我没时间聊天，朋友，但如果你愿意帮我们对付兽人，那我就帮你。" WHERE `entry`=382 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="嘿，$G老兄:夫人，你能帮我个忙吗？我现在真的很为难..." WHERE `entry`=415 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="嗨，$C。我的朋友，这是最糟糕的时刻，我们的城镇被围困了！黑石兽人正从石堡要塞发起攻击，古加尔隐现在伊尔加拉塔上空，赤脊山豺狼人正在积蓄力量。我希望你不是来这里度假的..." WHERE `entry`=464 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="问候：$c。如果你是库尔森上校的朋友，我就把你砍了！但是如果你是来帮助我们的，请听我说..." WHERE `entry`=469 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="黑暗的时代来了，$c...我们很快就会失去一切...当光明抛弃了一切，只留下那些真正在光明下行走的人。" WHERE `entry`=633 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="到处都是小偷！ $b$b太可怕了。 洞穴就在我们上方。 我认为矿业公司已经死了，包括我的兄弟，工头。" WHERE `entry`=656 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="卡尔文家族在光明之下争取胜利。 我在光明下的职责就是在他们与亡灵的战斗中献出我的生命。 卡尔文大师派我在暮色森林消灭邪恶的狼人。 也许你会帮助我？" WHERE `entry`=663 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="你知道，我一直想成为一名勘探者，但我天生对数字很有头脑，公会决定我最适合保存这些书！学习，学习，我青春的每一天…" WHERE `entry`=1105 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="你好，朋友。 名字是布瑞尔，布瑞尔的执政官，确切地说。我负责监督塞尔萨玛，相信你，我们总能在这里使用另一个强大的武器！" WHERE `entry`=1139 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="如果您来这里是为了美食，那么欢迎您！你不会在暴风城...或者艾泽拉斯的其它地方找到更好的饮食了！$B$B如果你有其它事情，那么请简短描述。我准备了十几道菜，每一道菜都得品尝。" WHERE `entry`=1141 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="如果你愿意忍受那些会让你浑身发抖、毛骨悚然的故事，那就去喝一杯，坐一会儿..." WHERE `entry`=1239 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="穴居人！我发誓上帝把他们放在这片土地上只是为了折磨我！深入地下四英寸，然后离穴居人还有两英尺远！" WHERE `entry`=1254 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="欢迎来到由奥瑞克斯·雷酿创建雷酿酒窖。自从我的哥哥（格里姆博泽）在一些醉酒的阴霾中消失以来，我就一直在这个地方经营..." WHERE `entry`=1267 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="虽然我们正在这些废墟上艰难地度过一段缓慢的时期，但我相信这不会持续太久。但在此期间，我需要你这样的人。你愿意帮助矮人探险协会吗?" WHERE `entry`=1344 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="我正处于一项非常重要的任务中。 探矿者业务。 除非你有一些同样重要的话要说，我怀疑，那你就不得不原谅我。" WHERE `entry`=1356 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="你不会找到一个比暴风皇家图书馆更大的知识宝库了！" WHERE `entry`=1440 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="大家好，我是巴隆斯·阿历克斯顿，暴风城的建筑师。" WHERE `entry`=1646 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="在这里，你这个没用的...！如果你想做一些有用的事情，听我说！" WHERE `entry`=1719 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="我是伯瓦尔·弗塔根。暴风城的大领主。" WHERE `entry`=1748 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="我是为公共服务而受教育的。人民的代表。我的技巧不在于武器或手艺，而在于言辞和说服力。" WHERE `entry`=1977 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="发动机引擎是每个飞行员的骄傲！" WHERE `entry`=2092 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="问候：$c。我现在手头有点紧，兽皮不够用了。" WHERE `entry`=2094 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="回去！留下来！我有一袋爆破粉，我不怕用它！ 我要把我们都吹走！$B$B，噢，没关系。我以为你是别人..." WHERE `entry`=2785 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="欢迎到贝尔杜加斯的符文和厄运，$c。你可以看，但不要摸。这里的一些知识并不适合你...你是外行。" WHERE `entry`=2786 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="让我告诉你，这是一个很大的偏离，$c。我们抓住了任何没有被钉牢的东西，或者可以迅速移除的东西。正因为如此，我们的补给品有点短缺。" WHERE `entry`=2860 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="在我们喝了几杯之后，那些强盗就来到了我们身边。 否则，我们可以干掉他们，相信我。$B$B每个人现在已经死了...除了我们中的一些人。" WHERE `entry`=2910 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="嘿，$N.$N.$B$BLotwil's不是我遇到过的最有洞察力的老板。他对自己的工作非常投入。以至于有时他的仆人不吃饭，也拿不到钱。但是这并不意味着你应该受苦。" WHERE `entry`=2920 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="美好的一天，$g小伙子:小姑娘;！也许你能帮我处理一些需要处理的事情。" WHERE `entry`=3663 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="嗯...我可以把这条电线插在这里，为fizzletan齿轮提供动力，但是检漏器需要一个备用电源...也许我可以...！嘿，想帮我试试新发明吗？" WHERE `entry`=3666 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="你好，朋友。我能为您做些什么？" WHERE `entry`=4078 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="不，长耳朵不是我的真名。我不会告诉你们这是什么，所以不要问。" WHERE `entry`=4456 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="有些人认为沼泽不好...他们说不行。" WHERE `entry`=4792 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="联盟在凄凉之地有很多利害关系，而我们在这里的控制是不稳定的。你愿意帮助我们吗？" WHERE `entry`=5396 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="我在凄凉之地有很多事要做，$N。Roetten想让我们为我们的一个客户挑选一些试剂，同时取回一些丢失的物品。既然你是来帮忙的，我们为什么不开始呢？" WHERE `entry`=5638 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="有些人无法忍受大熔炉的高温，但我认为高温恰到好处。这是做一些严肃的铁匠铺的最好的地方。" WHERE `entry`=6031 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="许多等待圣光测试的圣骑士，$N. 请放心，如果你保持激情，坚持我们所赞美的美德，我们的道路将在未来多次相遇。" WHERE `entry`=6179 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="我们的家--诺姆瑞根，就在特罗格斯和麻疯病侏儒漫步的地方。$B$B我们丢失了我们的家庭，我们的家园流离失所。我多么渴望无忧无虑的日子啊，诺姆瑞根生活，但那些日子已经没有了。我们必须站起来！我们必须挽救诺姆瑞根！" WHERE `entry`=6569 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="为了诺姆瑞根！" WHERE `entry`=6579 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="我从来没有错过..." WHERE `entry`=9081 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="立正，士兵! $B$BWINKY!SOUND OFF!" WHERE `entry`=9177 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="你好，$R。" WHERE `entry`=9562 AND `type`=0;
UPDATE `quest_greeting` SET `content_loc4`="欢迎来到Kibler's的奇异宠物店!今天你能帮我什么忙？" WHERE `entry`=10260 AND `type`=0;
